Repository crc-org/crc, pull requests merged in 2020-09, with the labels that each got.

#1442 Move usage message in cmd package
  cmd/crc/cmd/start.go
  pkg/crc/machine/machine.go
Labels: approved, lgtm

#1502 Fix crc setup expected output in integration tests
  test/integration/features/basic.feature
Labels: approved, lgtm

#1503 Fix crc cleanup expected output in integration tests
  pkg/crc/systemd/systemd.go
  test/integration/features/basic.feature
Labels: approved, lgtm

#1504 integration: Fix NetworkManager preflight messages
  test/integration/features/basic.feature
Labels: approved, do-not-merge/hold, lgtm

#1508 install Makefile target uses same ldflags as others targets
  Makefile
Labels: approved, lgtm

#1510 Update bundle from 4.5.7 to 4.5.8
  Makefile
  centos_ci.sh
Labels: approved, lgtm

#1514 Remove the extra validation for bundleName
  pkg/crc/machine/machine.go
Labels: approved, lgtm

#1494 Issue #1492 Only windows 10 Home edition doesn't support Hyperv
  docs/source/topics/ref_minimum-system-requirements.adoc
  pkg/crc/preflight/preflight_checks_windows.go
Labels: approved, lgtm

#1515 Docs: Add port 443 to remote haproxy configuration
  docs/source/topics/proc_setting-up-remote-server.adoc
Labels: approved, lgtm

#1518 Update bundle from 4.5.8 to 4.5.9
  Makefile
  centos_ci.sh
Labels: approved, do-not-merge/hold

#1519 cut v1.16.0
  Makefile
Labels: approved

#1523 Improve version mismatch wording
  pkg/crc/cache/cache.go
Labels: approved, lgtm

#1528 Host IP is not necessary anymore in startup sequence
  pkg/crc/machine/machine.go
  pkg/crc/network/utils.go
  pkg/crc/services/services.go
Labels: approved, lgtm

#1536 Workaround vbom.ml breakage
  go.mod
  go.sum
Labels: approved, lgtm

#1535 Only check bundle version if the bundle is embedded
  pkg/crc/validation/validation.go
Labels: approved, lgtm

#1529 Better display MultiError when errors are the same
  pkg/crc/api/handlers.go
  pkg/crc/errors/multierror.go
  pkg/crc/errors/multierror_test.go
Labels: approved, lgtm

#1540 Get golangci-lint binary without updating go mod
  Makefile
Labels: approved, lgtm

#1544 Update bundle from 4.5.9 to 4.5.11
  Makefile
  centos_ci.sh
Labels: approved, lgtm

#1547 Remove handling of GetOpenshiftVersion() returning ""
  pkg/crc/machine/machine.go
Labels: approved, lgtm

#1546 Remove unused DriverName field
  pkg/crc/machine/machine.go
  pkg/crc/services/services.go
Labels: approved, lgtm

#1533 Only send logs to stderr
  pkg/crc/logging/logging.go
  pkg/crc/logging/stderr_hook.go
  pkg/crc/logging/stdout_hook.go
  test/integration/features/basic.feature
  test/integration/features/config.feature
Labels: approved, lgtm

#1543 Add unit tests for preflight checks
  pkg/crc/preflight/preflight_test.go
Labels: approved, lgtm

#1553 Fix display of non-string value in SuccessfullyApplied callback
  pkg/crc/config/callbacks.go
  pkg/crc/config/callbacks_test.go
Labels: approved
