Repository crc-org/crc, pull requests merged in 2020-11, with the labels that each got.

#1598 Collect more data if CI encounters a failure
  go.mod
  go.sum
  test/integration/crcsuite/collect.go
  test/integration/crcsuite/crcsuite.go
  vendor/golang.org/x/sync/AUTHORS
  vendor/golang.org/x/sync/CONTRIBUTORS
  vendor/golang.org/x/sync/LICENSE
  vendor/golang.org/x/sync/PATENTS
  vendor/golang.org/x/sync/semaphore/semaphore.go
  vendor/modules.txt
Labels: approved, lgtm

#1641 Give more memory to the VM in health e2e test
  test/integration/features/story_health.feature
Labels: approved, lgtm

#1634 delete: Fix message when user refuses cluster deletion
  cmd/crc/cmd/delete.go
  cmd/crc/cmd/delete_test.go
Labels: approved, lgtm

#1653 Bump libmachine. No more RPC for hyperv driver.
  go.mod
  go.sum
  test/integration/crcsuite/collect.go
  vendor/github.com/code-ready/machine/libmachine/drivers/utils.go
  vendor/github.com/code-ready/machine/libmachine/host/host.go
  vendor/github.com/code-ready/machine/libmachine/libmachine.go
  vendor/github.com/code-ready/machine/libmachine/ssh/client.go
  vendor/github.com/code-ready/machine/libmachine/ssh/keys.go
  vendor/github.com/code-ready/machine/libmachine/ssh/keys_unix.go
  vendor/github.com/code-ready/machine/libmachine/ssh/keys_windows.go
  vendor/modules.txt
Labels: approved, lgtm

#1668 machine: Only call makeDaemonVisibleToHyperkit() when vsock is used
  pkg/crc/machine/machine.go
Labels: approved, lgtm

#1656 Allow to resize disk when machine is created
  pkg/crc/machine/config/config.go
  pkg/crc/machine/config/driver.go
  pkg/crc/machine/driver.go
  pkg/crc/machine/machine.go
Labels: approved, lgtm

#1662 Docs: separate port 80 and 443 remote haproxy sections
  docs/source/topics/proc_setting-up-remote-server.adoc
Labels: approved, lgtm, needs-ok-to-test

#1671 Issue #1643: Docs: Fix commands to enable monitoring on Windows
  docs/source/topics/proc_starting-monitoring-alerting-telemetry.adoc
Labels: approved, lgtm

#1669 cmd/start: Remove duplicate message
  cmd/crc/cmd/start.go
  cmd/crc/cmd/start_test.go
Labels: approved, lgtm

#1672 Docs: Update `odo` command with `--s2i` flag
  docs/source/topics/proc_deploying-sample-application-with-odo.adoc
Labels: approved, lgtm

#1664 hyperv driver is directly created by libmachine
  cmd/crc/main.go
  pkg/crc/machine/client/client_darwin.go
  pkg/crc/machine/client/client_linux.go
  pkg/crc/machine/client/client_windows.go
  vendor/github.com/code-ready/machine/libmachine/drivers/plugin/register_driver.go
  vendor/modules.txt
Labels: approved, lgtm

#1630 crc setup prepares everything before crc start even bundle extraction
  pkg/crc/preflight/preflight_checks_common.go
  test/integration/features/basic.feature
  test/integration/features/config.feature
Labels: approved

#1713 Fix travis CI
  .travis.yml
Labels: approved, lgtm

#1702 Issue #1690 cert_recovery: put time back manually
  test/integration/features/cert_rotation.feature
Labels: approved, lgtm

#1719 Improve os.MkdirAll use
  pkg/crc/cache/cache.go
  pkg/crc/constants/constants.go
  pkg/crc/machine/bundle/metadata.go
  pkg/crc/preflight/preflight_checks_tray_darwin.go
  pkg/extract/extract.go
Labels: approved, lgtm

#1700 Adding the ability to build CRC with an embedded OKD bundle.
  Makefile
  cmd/crc/cmd/start.go
  cmd/crc/cmd/start_test.go
  pkg/crc/constants/constants.go
  pkg/crc/version/version.go
Labels: approved, lgtm, ok-to-test

#1586 Restart openshift-apiserver only if aggregator-client-ca is expired
  pkg/crc/cluster/cert-renewal.go
  pkg/crc/cluster/cluster.go
  pkg/crc/machine/machine.go
Labels: approved, lgtm

#1726 Issue #1724: Do not use Dockerhub centos images
  images/openshift-ci/Dockerfile
  images/squid/Dockerfile
  test/testdata/Dockerfile
Labels: approved, lgtm

#1731 Docs: Disable automatic URL for the OpenShift console
  docs/source/topics/proc_connecting-to-remote-instance.adoc
Labels: approved, lgtm
