Repository crc-org/crc, pull requests merged in 2020-12, with the labels that each got.

#1715 Update bundle from 4.6.3 to 4.6.6
  Makefile
  centos_ci.sh
Labels: approved, do-not-merge/hold

#1748 preflight: Rename dispatcher file config option
  pkg/crc/preflight/preflight_checks_network_linux.go
Labels: approved, lgtm

#1744 Remove network manager and dnsmasq config in case systemd-resolved active
  pkg/crc/preflight/preflight_checks_network_linux.go
Labels: approved

#1752 Update libvirt machine driver to 0.12.13
  pkg/crc/machine/libvirt/constants.go
Labels: approved, lgtm

#1755 cleanup: Don't error out when hyperkit is not running
  pkg/crc/preflight/preflight_checks_darwin.go
Labels: approved, lgtm

#1741 Issue #1418 Document accessing the internal registry
  docs/source/topics/assembly_accessing-the-openshift-cluster.adoc
  docs/source/topics/proc_accessing-the-internal-openshift-registry.adoc
Labels: approved

#1756 cut v1.20.0
  Makefile
Labels: approved, lgtm

#1759 Issue #1490: Better recognize disk usage by regex
  test/integration/features/basic.feature
Labels: approved, lgtm

#1754 Bump libmachine, remove unused code
  go.mod
  go.sum
  pkg/crc/constants/constants.go
  pkg/crc/machine/config/driver.go
  pkg/crc/machine/machine.go
  vendor/github.com/code-ready/machine/drivers/errdriver/error.go
  vendor/github.com/code-ready/machine/drivers/hyperv/hyperv.go
  vendor/github.com/code-ready/machine/drivers/none/driver.go
  vendor/github.com/code-ready/machine/libmachine/auth/auth.go
  vendor/github.com/code-ready/machine/libmachine/drivers/base.go
  vendor/github.com/code-ready/machine/libmachine/drivers/check.go
  vendor/github.com/code-ready/machine/libmachine/drivers/drivers.go
  vendor/github.com/code-ready/machine/libmachine/drivers/notsupported.go
  vendor/github.com/code-ready/machine/libmachine/drivers/plugin/localbinary/plugin.go
  vendor/github.com/code-ready/machine/libmachine/drivers/rpc/client_driver.go
  vendor/github.com/code-ready/machine/libmachine/drivers/rpc/server_driver.go
  vendor/github.com/code-ready/machine/libmachine/engine/engine.go
  vendor/github.com/code-ready/machine/libmachine/host/host.go
  vendor/github.com/code-ready/machine/libmachine/host/host_v0.go
  vendor/github.com/code-ready/machine/libmachine/host/host_v2.go
  vendor/github.com/code-ready/machine/libmachine/host/migrate.go
  vendor/github.com/code-ready/machine/libmachine/host/migrate_v0_v1.go
  vendor/github.com/code-ready/machine/libmachine/host/migrate_v1_v2.go
  vendor/github.com/code-ready/machine/libmachine/host/migrate_v2_v3.go
  vendor/github.com/code-ready/machine/libmachine/libmachine.go
  vendor/github.com/code-ready/machine/libmachine/mcnerror/errors.go
  vendor/github.com/code-ready/machine/libmachine/mcnflag/flag.go
  vendor/github.com/code-ready/machine/libmachine/persist/filestore.go
  vendor/github.com/code-ready/machine/libmachine/persist/store.go
  vendor/github.com/code-ready/machine/libmachine/swarm/swarm.go
  vendor/modules.txt
Labels: approved

#1779 Return stderr in case of err for ssh commands
  pkg/crc/ssh/ssh.go
Labels: approved, lgtm

#1774 Add flag to crc start to automatically turn on monitoring stack
  cmd/crc/cmd/config/config.go
  cmd/crc/cmd/start.go
  pkg/crc/cluster/monitoring.go
  pkg/crc/machine/machine.go
  pkg/crc/machine/types.go
Labels: approved, lgtm

#1780 Add wait for apiserver function
  pkg/crc/cluster/cluster.go
  pkg/crc/machine/machine.go
Labels: approved, lgtm

#1761 Initial telemetry implementation
  cmd/crc/cmd/config/config.go
  cmd/crc/cmd/root.go
  cmd/crc/cmd/start.go
  go.mod
  go.sum
  pkg/crc/segment/segment.go
  pkg/crc/segment/segment_test.go
  pkg/crc/ssh/client.go
  vendor/github.com/segmentio/analytics-go/.gitignore
  vendor/github.com/segmentio/analytics-go/.gitmodules
  vendor/github.com/segmentio/analytics-go/History.md
  vendor/github.com/segmentio/analytics-go/License.md
  vendor/github.com/segmentio/analytics-go/Makefile
  vendor/github.com/segmentio/analytics-go/Readme.md
  vendor/github.com/segmentio/analytics-go/alias.go
  vendor/github.com/segmentio/analytics-go/analytics.go
  vendor/github.com/segmentio/analytics-go/config.go
  vendor/github.com/segmentio/analytics-go/context.go
  vendor/github.com/segmentio/analytics-go/error.go
  vendor/github.com/segmentio/analytics-go/executor.go
  vendor/github.com/segmentio/analytics-go/group.go
  vendor/github.com/segmentio/analytics-go/identify.go
  vendor/github.com/segmentio/analytics-go/integrations.go
  vendor/github.com/segmentio/analytics-go/json.go
  vendor/github.com/segmentio/analytics-go/logger.go
  vendor/github.com/segmentio/analytics-go/message.go
  vendor/github.com/segmentio/analytics-go/page.go
  vendor/github.com/segmentio/analytics-go/properties.go
  vendor/github.com/segmentio/analytics-go/screen.go
  vendor/github.com/segmentio/analytics-go/timeout_15.go
  vendor/github.com/segmentio/analytics-go/timeout_16.go
  vendor/github.com/segmentio/analytics-go/track.go
  vendor/github.com/segmentio/analytics-go/traits.go
  vendor/github.com/segmentio/backo-go/.gitmodules
  vendor/github.com/segmentio/backo-go/LICENSE
  vendor/github.com/segmentio/backo-go/README.md
  vendor/github.com/segmentio/backo-go/backo.go
  vendor/github.com/segmentio/backo-go/go.mod
  vendor/github.com/xtgo/uuid/AUTHORS
  vendor/github.com/xtgo/uuid/LICENSE
  vendor/github.com/xtgo/uuid/uuid.go
  vendor/modules.txt
Labels: approved

#1800 ci: suppress progress bar from yum output
  centos_ci.sh
Labels: approved, lgtm

#1799 Split machine.go to multiples files. One per public method.
  pkg/crc/machine/client.go
  pkg/crc/machine/console.go
  pkg/crc/machine/delete.go
  pkg/crc/machine/exists.go
  pkg/crc/machine/ip.go
  pkg/crc/machine/machine.go
  pkg/crc/machine/poweroff.go
  pkg/crc/machine/start.go
  pkg/crc/machine/status.go
  pkg/crc/machine/stop.go
Labels: approved, lgtm

#1798 Add force flag only to delete and stop commands
  cmd/crc/cmd/delete.go
  cmd/crc/cmd/root.go
  cmd/crc/cmd/stop.go
Labels: approved, lgtm
