Repository crc-org/crc, pull requests merged in 2020-08, with the labels that each got.

#1433 cut v1.14.0
  Makefile
Labels: approved

#1428 Determine compress algorithm by checking magic bytes
  go.mod
  go.sum
  pkg/extract/extract.go
  pkg/extract/extract_test.go
  pkg/extract/testdata/test.tar
  vendor/github.com/h2non/filetype/.editorconfig
  vendor/github.com/h2non/filetype/.gitignore
  vendor/github.com/h2non/filetype/.travis.yml
  vendor/github.com/h2non/filetype/History.md
  vendor/github.com/h2non/filetype/LICENSE
  vendor/github.com/h2non/filetype/README.md
  vendor/github.com/h2non/filetype/filetype.go
  vendor/github.com/h2non/filetype/go.mod
  vendor/github.com/h2non/filetype/kind.go
  vendor/github.com/h2non/filetype/match.go
  vendor/github.com/h2non/filetype/matchers/application.go
  vendor/github.com/h2non/filetype/matchers/archive.go
  vendor/github.com/h2non/filetype/matchers/audio.go
  vendor/github.com/h2non/filetype/matchers/document.go
  vendor/github.com/h2non/filetype/matchers/font.go
  vendor/github.com/h2non/filetype/matchers/image.go
  vendor/github.com/h2non/filetype/matchers/isobmff/isobmff.go
  vendor/github.com/h2non/filetype/matchers/matchers.go
  vendor/github.com/h2non/filetype/matchers/video.go
  vendor/github.com/h2non/filetype/types/defaults.go
  vendor/github.com/h2non/filetype/types/mime.go
  vendor/github.com/h2non/filetype/types/split.go
  vendor/github.com/h2non/filetype/types/type.go
  vendor/github.com/h2non/filetype/types/types.go
  vendor/github.com/h2non/filetype/version.go
  vendor/modules.txt
Labels: approved, lgtm

#1431 Propogate errors outside of network package
  pkg/crc/network/utils.go
Labels: approved, lgtm

#1440 Fix formatting error in `crc start` documentation
  docs/source/topics/proc_starting-the-virtual-machine.adoc
Labels: approved, lgtm

#1439 exitHandlers are never used. Removing them.
  pkg/crc/exit/atexit.go
Labels: approved, lgtm

#1447 Update bundle version from 4.5.4 to 4.5.5
  Makefile
  centos_ci.sh
Labels: approved

#1415 Update proc_starting-monitoring-alerting-telemetry.adoc
  docs/source/topics/proc_starting-monitoring-alerting-telemetry.adoc
Labels: approved, lgtm, needs-ok-to-test

#1450 Add ssh test
  pkg/crc/ssh/ssh_test.go
Labels: approved

#1457 Issue #1175 Clarify required privilege elevation in docs
  docs/source/topics/proc_setting-up-codeready-containers.adoc
  docs/source/topics/proc_starting-the-virtual-machine.adoc
Labels: approved, lgtm

#1455 Check bundle presence by looking at bindata
  Makefile
  pkg/crc/constants/constants.go
Labels: approved, lgtm

#1463 Update libvirt driver from 0.12.8 to 0.12.9
  pkg/crc/machine/libvirt/constants.go
Labels: approved, lgtm

#1464 Bump hyperkit driver from 0.12.6 to 0.12.7
  pkg/crc/machine/hyperkit/constants.go
Labels: approved, lgtm

#1465 Remove kubeconfig file copy to instance
  pkg/crc/machine/machine.go
Labels: approved, lgtm

#1467 Update bundle from 4.5.5 to 4.5.6
  Makefile
  centos_ci.sh
Labels: approved

#1177 Add cleanup command to tests
  test/integration/features/basic.feature
  test/integration/features/cert_rotation.feature
  test/integration/features/proxy.feature
  test/integration/features/story_health.feature
  test/integration/features/story_marketplace.feature
  test/integration/features/story_registry.feature
Labels: approved, lgtm

#1443 Add feature to automate proxy ca cert
  cmd/crc/cmd/config/config.go
  cmd/crc/cmd/root.go
  docs/source/topics/proc_starting-codeready-containers-behind-proxy.adoc
  pkg/crc/cluster/cluster.go
  pkg/crc/machine/machine.go
  pkg/crc/network/proxy.go
Labels: approved, lgtm

#1475 Update bundle version from 4.5.6 to 4.5.7
  Makefile
  centos_ci.sh
Labels: approved

#1476 Bump tray version
  pkg/crc/version/version.go
Labels: approved, lgtm

#1479 Add win tray to embed data files
  cmd/crc-embedder/cmd/embed.go
  pkg/crc/constants/constants.go
  pkg/crc/preflight/preflight_check_tray_darwin.go
  pkg/crc/version/version.go
Labels: approved, lgtm

#1478 cut v1.15.0
  Makefile
Labels: approved, lgtm

#1482 Docs: fix odo install url
  docs/source/meta/product-attributes.adoc
Labels: approved, lgtm, needs-ok-to-test

#1483 Revert back to use of old libvirt-kvm-driver
  pkg/crc/machine/libvirt/constants.go
Labels: approved

#1489 config: Don't preallocate array in configurableFields
  cmd/crc/cmd/config/config.go
Labels: approved, lgtm

#1488 Add 10m timeout to golangci run to stop travis CI failure
  .golangci.yml
Labels: approved
