Repository crc-org/crc, pull requests merged in 2020-07, with the labels that each got.

#1350 preflight: macos: reset /etc/hosts permissions to 0644
  pkg/crc/preflight/preflight_checks_darwin.go
  pkg/crc/preflight/preflight_darwin.go
Labels: approved, lgtm

#1351 Add deployment config and deployment both for rollout status
  test/integration/features/story_health.feature
Labels: approved, lgtm

#1354 Bump clicumber
  go.mod
  go.sum
  vendor/github.com/code-ready/clicumber/testsuite/shell.go
  vendor/modules.txt
Labels: approved, lgtm

#1357 Fix formatting in documentation
  docs/source/topics/proc_starting-the-virtual-machine.adoc
  docs/source/topics/proc_upgrading-codeready-containers.adoc
  docs/source/topics/ref_minimum-system-requirements.adoc
Labels: approved, lgtm

#1353 Issue #1338 User user.Uid from os/user to get sid in windows
  pkg/os/windows/secpol/secpol_windows.go
Labels: approved, lgtm

#1365 Mention total # of retries in RetryAfter
  pkg/crc/errors/multierror.go
Labels: approved, lgtm

#1366 Update bundle from 4.5.0-rc.5 to 4.5.0-rc.6
  Makefile
  centos_ci.sh
Labels: approved, lgtm

#1367 Issue #1360 Explicitly mention Windows 10 Home is not supported
  docs/source/topics/ref_minimum-system-requirements.adoc
Labels: approved, lgtm

#1355 Refactor logging code
  cmd/crc-embedder/cmd/root.go
  cmd/crc/cmd/daemon.go
  cmd/crc/cmd/daemon_nonwin.go
  cmd/crc/cmd/daemon_windows.go
  cmd/crc/cmd/root.go
  pkg/crc/logging/file_hook.go
  pkg/crc/logging/logging.go
  pkg/crc/machine/machine.go
Labels: approved, lgtm

#1370 Update bundle version from 4.5.0-rc.6 to 4.5.0-rc.7
  Makefile
  centos_ci.sh
Labels: approved, lgtm

#1374 Issue #1358 Use links instead of xrefs in docs
  docs/source/meta/product-attributes.adoc
  docs/source/topics/proc_accessing-the-openshift-cluster-with-oc.adoc
  docs/source/topics/proc_accessing-the-openshift-web-console.adoc
  docs/source/topics/proc_deploying-sample-application-with-odo.adoc
  docs/source/topics/proc_getting-shell-access-to-the-openshift-cluster.adoc
  docs/source/topics/proc_installing-codeready-containers.adoc
  docs/source/topics/proc_starting-codeready-containers-behind-proxy.adoc
  docs/source/topics/proc_starting-monitoring-alerting-telemetry.adoc
  docs/source/topics/proc_starting-the-virtual-machine.adoc
  docs/source/topics/proc_troubleshooting-unknown-issues.adoc
  docs/source/topics/ref_minimum-system-requirements.adoc
Labels: approved, lgtm

#1379 Check that proxy URL starts with http:// or https://
  go.mod
  pkg/crc/network/proxy.go
  pkg/crc/network/proxy_test.go
  vendor/github.com/davecgh/go-spew/LICENSE
  vendor/github.com/davecgh/go-spew/spew/bypass.go
  vendor/github.com/davecgh/go-spew/spew/bypasssafe.go
  vendor/github.com/davecgh/go-spew/spew/common.go
  vendor/github.com/davecgh/go-spew/spew/config.go
  vendor/github.com/davecgh/go-spew/spew/doc.go
  vendor/github.com/davecgh/go-spew/spew/dump.go
  vendor/github.com/davecgh/go-spew/spew/format.go
  vendor/github.com/davecgh/go-spew/spew/spew.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/modules.txt
Labels: approved, lgtm

#1381 Update bundle from 4.5.0-rc.7 to 4.5.1
  Makefile
  centos_ci.sh
Labels: approved

#1382 cut v1.13.0
  Makefile
Labels: approved, lgtm

#1388 Embed: make errors as fatal for logging
  cmd/crc-embedder/cmd/embed.go
Labels: approved, lgtm

#1393 Remove the crc machine directory before removing the VM
  pkg/crc/preflight/preflight_checks_linux.go
Labels: approved, lgtm

#1392 Issue #679 Document using `htpasswd_provider` for the web console
  docs/source/topics/proc_accessing-the-openshift-web-console.adoc
Labels: approved, lgtm

#1404 Add unit test for api
  pkg/crc/api/api.go
  pkg/crc/api/api_test.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/modules.txt
Labels: approved, lgtm

#1400 Fix cache.Executable() check
  pkg/crc/cache/cache.go
  pkg/crc/preflight/preflight_checks_darwin.go
  pkg/crc/preflight/preflight_checks_linux.go
Labels: approved, lgtm

#1403 Remove license headers left over
  Makefile
  cmd/crc/cmd/console.go
  cmd/crc/cmd/version.go
  pkg/crc/errors/atexit.go
  pkg/crc/version/version.go
  test/integration/crcsuite/crcsuite.go
  test/integration/integration_test.go
Labels: approved, lgtm

#1407 Ensure the host has at least 9GB of RAM
  go.mod
  go.sum
  pkg/crc/preflight/preflight_checks_common.go
  pkg/crc/validation/validation.go
  vendor/github.com/pbnjay/memory/LICENSE
  vendor/github.com/pbnjay/memory/README.md
  vendor/github.com/pbnjay/memory/doc.go
  vendor/github.com/pbnjay/memory/memory_bsd.go
  vendor/github.com/pbnjay/memory/memory_darwin.go
  vendor/github.com/pbnjay/memory/memory_linux.go
  vendor/github.com/pbnjay/memory/memory_windows.go
  vendor/github.com/pbnjay/memory/memsysctl.go
  vendor/github.com/pbnjay/memory/stub.go
  vendor/modules.txt
Labels: approved, lgtm

#1408 Issue #1386 Run all oc commands from the VM
  pkg/crc/cluster/cluster.go
  pkg/crc/cluster/clusteroperator.go
  pkg/crc/cluster/clusteroperator_test.go
  pkg/crc/cluster/csr.go
  pkg/crc/machine/machine.go
  pkg/crc/oc/oc.go
Labels: approved, do-not-merge/hold, lgtm

#1416 Fix oc-env command error in windows
  pkg/os/shell/shell.go
Labels: approved, lgtm

#1419 Use existing template to create application
  test/integration/features/story_health.feature
Labels: approved, lgtm

#1375 Issue #1238 Document non-customizable cluster settings
  docs/source/topics/con_differences-from-production-openshift-install.adoc
Labels: approved, lgtm

#1397 Update bundle version from 4.5.1 to 4.5.4
  Makefile
  centos_ci.sh
Labels: approved

#1424 Issue #1423 Add VPN note to `crc start` documentation
  docs/source/topics/proc_starting-the-virtual-machine.adoc
Labels: approved, lgtm
