Repository crc-org/crc, pull requests merged in 2021-02, with the labels that each got.

#1919 Update bundle to 4.6.13 from 4.6.12
  Makefile
  centos_ci.sh
Labels: approved, lgtm

#1921 Daemon should exit with an error if it can't accept connections
  pkg/crc/api/api.go
Labels: approved, lgtm

#1926 #1903 aborting extract doesn't corrupt cache directory
  pkg/crc/machine/bundle/repository.go
Labels: approved, lgtm

#1930 macos: Rename installer to crc-installer-macos-amd64.pkg
  Makefile
Labels: approved, lgtm

#1929 Remove extra line in crc start output
  cmd/crc/cmd/start.go
  cmd/crc/cmd/start_test.go
Labels: approved

#1936 [Segment] Capture crc run on tty/non-tty environment
  pkg/crc/segment/segment.go
Labels: approved, lgtm

#1941 Update bundle from 4.6.13 to 4.6.15
  Makefile
  centos_ci.sh
Labels: approved

#1855 Rename integration tests to e2e tests
  Makefile
  centos_ci.sh
  developing.adoc
  test/e2e/crcsuite/collect.go
  test/e2e/crcsuite/crcsuite.go
  test/e2e/crcsuite/prepare.go
  test/e2e/crcsuite/util.go
  test/e2e/e2e_test.go
  test/e2e/features/basic.feature
  test/e2e/features/cert_rotation.feature
  test/e2e/features/config.feature
  test/e2e/features/proxy.feature
  test/e2e/features/story_health.feature
  test/e2e/features/story_marketplace.feature
  test/e2e/features/story_registry.feature
Labels: approved, lgtm

#1943 os: Add RunningInTerminal() helper
  pkg/crc/cluster/pullsecret.go
  pkg/crc/input/input.go
  pkg/crc/segment/segment.go
  pkg/os/util.go
Labels: approved, lgtm

#1920 Report status as "Unreachable" instead of "Not Reachable"
  pkg/crc/machine/status.go
Labels: approved, lgtm

#1939 Fix ValidateBool function to accept valid range of boolean
  pkg/crc/config/validations.go
Labels: approved, lgtm

#1947 #1927 write config to a temporary file and then rename it
  pkg/crc/config/viper_config.go
Labels: approved

#1951 Check the tray version when checking if tray executable exists
  pkg/crc/preflight/preflight_checks_tray_windows.go
Labels: approved, lgtm, os/windows

#1953 Bump crc trays' version
  pkg/crc/version/version.go
Labels: approved, lgtm

#1955 Small fixes for the logger
  cmd/crc/cmd/daemon.go
  cmd/crc/cmd/root.go
Labels: approved, lgtm

#1949 #1948 don't use viper to write the config file
  pkg/crc/config/viper_config.go
  pkg/crc/config/viper_config_test.go
Labels: approved, lgtm

#1958 Use regex to replace the carriage return to '\n' char
  pkg/crc/cluster/cluster.go
Labels: approved, lgtm

#1959 cut 1.22.0
  Makefile
Labels: approved, lgtm

#1968 Add latest version check in version command
  cmd/crc/cmd/version.go
Labels: approved, lgtm

#1969 Update bundle from 4.6.15 to 4.6.16
  Makefile
  centos_ci.sh
Labels: approved

#1971 Fix 'CodeReady Container' typo
  images/dnsmasq/Dockerfile
  images/squid/Dockerfile
Labels: approved, lgtm

#1974 Fix #1874 Do not run preflights if VM already running
  cmd/crc/cmd/start.go
  pkg/crc/machine/client.go
  pkg/crc/machine/fakemachine/client.go
  pkg/crc/machine/start.go
Labels: approved

#1977 vsock: allow the VM to reach host services.
  cmd/crc/cmd/daemon.go
Labels: approved, lgtm

#1982 Update crc landing page url
  README.adoc
  docs/source/meta/product-attributes.adoc
  docs/source/topics/proc_starting-the-virtual-machine.adoc
  pkg/crc/constants/constants.go
Labels: approved, lgtm

#1980 Extract the bundle at the end of crc setup
  pkg/crc/preflight/preflight_checks_common.go
  pkg/crc/preflight/preflight_darwin.go
  pkg/crc/preflight/preflight_linux.go
  pkg/crc/preflight/preflight_linux_test.go
  pkg/crc/preflight/preflight_windows.go
Labels: approved, lgtm

#1979 Increase apiserver wait time for a min
  pkg/crc/cluster/cluster.go
Labels: approved, lgtm

#1988 crc-admin context is not reliable on the CI. Keep using oc login.
  test/e2e/features/basic.feature
Labels: approved, lgtm

#1984 Add error type to segment
  pkg/crc/segment/segment.go
  pkg/crc/segment/segment_test.go
Labels: approved, lgtm

#1992 Change the error message when running as root on Windows
  pkg/crc/preflight/preflight_checks_windows.go
  pkg/crc/preflight/preflight_windows.go
Labels: approved, lgtm

#1975 Change the cluster started summary
  cmd/crc/cmd/oc_env.go
  cmd/crc/cmd/podman_env.go
  cmd/crc/cmd/start.go
  cmd/crc/cmd/start_test.go
  pkg/os/shell/shell.go
  test/e2e/features/basic.feature
Labels: approved

#1995 docs: Amend reference to "OpenShift Do"
  docs/source/topics/proc_deploying-sample-application-with-odo.adoc
Labels: approved, lgtm

#1996 docs: Remove reference to `htpasswd_provider`
  docs/source/topics/proc_accessing-the-openshift-web-console.adoc
Labels: approved, lgtm

#1999 Remove code that changes the proxy env. variable in crc status
  pkg/crc/machine/status.go
Labels: approved, lgtm

#1882 Prepare an archive with everything to build the macOS pkg. Add codesign.
  .circleci/config.yml
  Makefile
  packaging/package.sh
Labels: approved, lgtm

#2010 Mask username from error before sending to segment
  pkg/crc/segment/segment.go
  pkg/crc/telemetry/telemetry.go
  pkg/crc/telemetry/telemetry_test.go
Labels: approved, lgtm

#2012 oc commands running in a retry loop can have a 5s timeout. Increase to 30s for others.
  pkg/crc/cluster/cert-renewal.go
  pkg/crc/cluster/cluster.go
  pkg/crc/cluster/clusteroperator.go
  pkg/crc/cluster/csr.go
  pkg/crc/oc/oc.go
  pkg/crc/oc/oc_linux_test.go
Labels: approved

#2015 Remove setup output checks which differ across linux flavours
  test/e2e/features/basic.feature
  test/e2e/features/config.feature
Labels: approved, lgtm

#2016 centos-ci: fix uploading artifacts for master branch job
  centos_ci.sh
Labels: approved, lgtm

#2021 docs: Use admin permissions for `oc get co`
  docs/source/topics/proc_accessing-the-openshift-cluster-with-oc.adoc
Labels: approved, lgtm

#2018 add details to telemetry about libvirt network failure
  pkg/crc/preflight/preflight_checks_linux.go
Labels: approved, lgtm

#2005 Telemetry notice
  README.adoc
  usage-data.adoc
Labels: approved, lgtm

#2025 Don't enable host network access by default
  cmd/crc/cmd/config/config.go
  cmd/crc/cmd/daemon.go
Labels: approved, has-to-be-in-release, lgtm
