Repository crc-org/crc, pull requests merged in 2021-11, with the labels that each got.

#2825 Update openshift bundle to 4.9.5 (candidate channel)
  Makefile
  centos_ci.sh
Labels: lgtm, approved

#2822 docs: Fix small errors, adhere to Red Hat style
  docs/source/meta/product-attributes.adoc
  docs/source/topics/assembly_accessing-the-openshift-cluster.adoc
  docs/source/topics/con_about-codeready-containers.adoc
  docs/source/topics/con_differences-from-production-openshift-install.adoc
  docs/source/topics/proc_accessing-the-internal-openshift-registry.adoc
  docs/source/topics/proc_accessing-the-openshift-cluster-with-oc.adoc
  docs/source/topics/proc_accessing-the-openshift-web-console.adoc
  docs/source/topics/proc_connecting-to-remote-instance.adoc
  docs/source/topics/proc_deploying-sample-application-with-odo.adoc
  docs/source/topics/proc_getting-shell-access-to-the-openshift-cluster.adoc
  docs/source/topics/proc_installing-codeready-containers.adoc
  docs/source/topics/proc_setting-up-codeready-containers.adoc
  docs/source/topics/proc_setting-up-remote-server.adoc
  docs/source/topics/proc_starting-codeready-containers-behind-proxy.adoc
  docs/source/topics/proc_starting-monitoring-alerting-telemetry.adoc
  docs/source/topics/proc_starting-the-virtual-machine.adoc
  docs/source/topics/proc_troubleshooting-expired-certificates.adoc
  docs/source/topics/proc_troubleshooting-unknown-issues.adoc
  docs/source/topics/ref_dns-configuration.adoc
Labels: kind/documentation, status/peer review required, lgtm, approved

#2828 Improve usage hint of crc podman-env --root
  cmd/crc/cmd/podman_env.go
Labels: lgtm, approved, needs-ok-to-test

#2831 cut v1.35.0
  Makefile
Labels: lgtm, approved, do-not-merge/hold

#2849 Update admin helper from 0.0.7 to 0.0.8
  pkg/crc/constants/constants.go
Labels: lgtm, approved

#2851 Update bundle version to Openshift 4.9.8 (stable channel)
  Makefile
  centos_ci.sh
Labels: lgtm, approved

#2854 e2e: Remove --bundle-version
  Makefile
  images/build-e2e/entrypoint.sh
  test/e2e/crcsuite/crcsuite.go
Labels: lgtm, approved
