Repository crc-org/crc, pull requests merged in 2021-04, with the labels that each got.

#2163 Change install path of crc to /Applications/CodeReady Containers.app
  Makefile
  packaging/.gitignore
  packaging/darwin/postinstall.in
  packaging/package.sh
  pkg/crc/constants/constants.go
  pkg/crc/constants/constants_darwin.go
  pkg/embed/embed.go
Labels: approved, lgtm

#2184 Update bundle from 4.7.4 to 4.7.5
  Makefile
  centos_ci.sh
Labels: approved, lgtm

#2161 Ask the user to stop the application before updating
  packaging/darwin/Distribution.in
Labels: approved, lgtm

#2187 Bump macOS tray to 1.0.6
  pkg/crc/version/version.go
Labels: lgtm

#2189 Ignore clean host file error in case admin helper binary is not present
  pkg/crc/preflight/preflight_checks_nonwin.go
  pkg/crc/preflight/preflight_linux_test.go
Labels: approved, lgtm

#2197 Update macOS tray to 1.0.7
  pkg/crc/version/version.go
Labels: approved, lgtm

#2200 Fix kubeconfig update on restarts
  pkg/crc/cluster/kubeadmin_password.go
  pkg/crc/machine/start.go
Labels: approved, lgtm

#2179 Add --check-only to crc setup
  cmd/crc/cmd/setup.go
  cmd/crc/cmd/setup_test.go
  test/e2e/features/basic.feature
  test/integration/resize_test.go
Labels: approved, has-to-be-in-release, lgtm

#2196 [E2E] Fix cleanup expected output on MacOS to common minimum expected information
  test/e2e/features/basic.feature
Labels: has-to-be-in-release, lgtm

#2207 Rework waitForNetwork
  pkg/crc/services/dns/dns_darwin.go
Labels: approved, has-to-be-in-release

#2208 cut v1.25.0
  Makefile
Labels: approved

#2212 vsock: check daemon is running in machine.Start instead of preflights
  pkg/crc/machine/vsock.go
  pkg/crc/preflight/preflight_checks_nondarwin.go
  pkg/crc/preflight/preflight_linux.go
  pkg/crc/preflight/preflight_linux_test.go
  pkg/crc/preflight/preflight_windows.go
  pkg/crc/preflight/preflight_windows_test.go
Labels: approved, lgtm

#2210 [Segment] Capture SSH_TTY env
  pkg/crc/segment/segment.go
  pkg/crc/segment/segment_test.go
  pkg/os/util.go
  usage-data.adoc
Labels: approved, lgtm

#2209 pkg: remove destination select step
  packaging/darwin/Distribution.in
Labels: approved, lgtm

#2218 cleanup: Use pkill -9 to remove the hyperkit process
  pkg/crc/preflight/preflight_checks_darwin.go
Labels: approved, lgtm

#2219 Prettify data usage doc
  usage-data.adoc
Labels: approved, lgtm

#2217 start: Add log with VM's IP when it started
  pkg/crc/machine/start.go
Labels: approved, lgtm

#2224 vsock: expose port 80
  pkg/crc/machine/vsock.go
Labels: approved, lgtm

#2235 Fix grammatical error in error message
  cmd/crc/cmd/start.go
Labels: approved, lgtm

#2238 docs: Amend minimum CPU requirements
  docs/source/topics/ref_minimum-system-requirements.adoc
Labels: approved, lgtm

#2239 Update bundle from 4.7.5 to 4.7.7
  Makefile
  centos_ci.sh
Labels: approved, lgtm

#2233 docs: Rework cert renewal troubleshooting
  docs/source/topics/proc_troubleshooting-expired-certificates.adoc
Labels: approved, lgtm

#2237 Add another format to check capabilities
  pkg/crc/preflight/preflight_linux.go
Labels: approved, lgtm

#2268 Use container runtime as docker for doc build
  .circleci/config.yml
Labels: approved, lgtm

#2252 #2206 macOS pkg: use hyperkit, driver and admin-helper directly from app dir
  packaging/package.sh
  pkg/crc/adminhelper/hosts.go
  pkg/crc/constants/constants.go
  pkg/crc/machine/driver_darwin.go
  pkg/crc/machine/hyperkit/driver_darwin.go
  pkg/crc/preflight/preflight_checks_common.go
  pkg/crc/preflight/preflight_checks_darwin.go
Labels: approved, lgtm

#2270 Remove warn message for local dns reachable in case of vsock
  pkg/crc/machine/start.go
Labels: approved, lgtm

#2257 Remove generation of PDF documentation
  Makefile
  images/docs-builder/Dockerfile
  images/docs-builder/entrypoint.sh
Labels: approved, lgtm

#2274 Bump macOS tray to v1.0.8. It adds telemetry.
  pkg/crc/version/version.go
Labels: approved, has-to-be-in-release, lgtm

#2275 Remove podman preflight check. Podman is already included in the bundle.
  pkg/crc/cache/cache.go
  pkg/crc/constants/constants.go
  pkg/crc/constants/constants_darwin.go
  pkg/crc/constants/constants_linux.go
  pkg/crc/constants/constants_windows.go
  pkg/crc/preflight/preflight_checks_common.go
  pkg/crc/preflight/preflight_darwin_test.go
  pkg/crc/preflight/preflight_linux_test.go
  pkg/crc/preflight/preflight_windows_test.go
Labels: approved, has-to-be-in-release, lgtm

#2283 Update golangci-lint
  Makefile
Labels: approved, lgtm

#2281 Issue #2276 Check if interface is nil before trying to convert it
  pkg/crc/api/handlers.go
Labels: approved, has-to-be-in-release

#2284 docs: Fix remote server instructions for rhel7
  docs/source/topics/proc_setting-up-remote-server.adoc
Labels: approved, has-to-be-in-release, kind/documentation, lgtm, os/linux, priority/major

#2282 Remove upgrade code that fixes /etc/hosts permissions on macOS
  pkg/crc/preflight/preflight_checks_darwin.go
  pkg/crc/preflight/preflight_darwin.go
  pkg/crc/preflight/preflight_darwin_test.go
Labels: approved

#2287 Run all setup preflights when --check-only is used
  cmd/crc/cmd/setup.go
  pkg/crc/preflight/preflight.go
  pkg/crc/preflight/preflight_test.go
Labels: approved, has-to-be-in-release, lgtm

#2289 [E2E] Remove e2e test for skip-check-hosts-file-permissions
  test/e2e/features/config.feature
Labels: has-to-be-in-release, lgtm

#2273 Use a release version of the routes controller (v0.0.1)
  pkg/crc/machine/start.go
Labels: approved, has-to-be-in-release, lgtm

#2090 Fix #2089 Update Windows tray assembly name
  pkg/crc/constants/constants_windows.go
Labels: approved, has-to-be-in-release, lgtm

#2292 Remove typos related to crc bundle generate
  pkg/crc/machine/bundle/metadata.go
  test/e2e/features/basic.feature
Labels: approved, lgtm

#2295 Update bundle from 4.7.7 to 4.7.8
  Makefile
  centos_ci.sh
Labels: approved, do-not-merge/hold
