Repository crc-org/crc, pull requests merged in 2021-07, with the labels that each got.

#2502 Issue #2499 Add error message to crc-users group preflight checks
  pkg/crc/preflight/preflight_windows.go
Labels: approved, has-to-be-in-release, lgtm

#2513 Issue #2499 Check if err is nil before returning
  pkg/crc/preflight/preflight_windows.go
Labels: approved, lgtm

#2515 Update bundle to 4.7.18
  Makefile
  centos_ci.sh
Labels: approved, do-not-merge/hold, lgtm

#2516 circleci: Update xcode version
  .circleci/config.yml
Labels: approved, lgtm

#2520 cut v1.29.0
  Makefile
Labels: approved

#2519 docs: Remove system network mode changes for macOS
  docs/source/topics/ref_dns-configuration.adoc
  docs/source/topics/ref_reserved-ip-subnets.adoc
Labels: approved, lgtm

#2524 Fix typo in start log message
  pkg/crc/cluster/cluster.go
Labels: approved, lgtm

#2549 Issue #2458 Ignore return value from hyperv installation custom action
  packaging/windows/product.wxs.in
Labels: approved, lgtm

#2544 Use redis operator for marketplace story
  test/e2e/features/story_marketplace.feature
  test/testdata/etcd-cluster3.yaml
  test/testdata/etcd-cluster5.yaml
  test/testdata/redis-cluster.yaml
  test/testdata/redis-sub.yaml
Labels: approved, lgtm

#2552 bump version to 1.29.1
  Makefile
Labels: approved, lgtm

#2564 [integration] disk resize test for macos
  test/integration/resize_test.go
Labels: approved, lgtm

#2562 Introduce a new type for crc status. Distinguish it from machine status.
  cmd/crc/cmd/console.go
  cmd/crc/cmd/status.go
  cmd/crc/cmd/stop.go
  pkg/crc/api/adapter.go
  pkg/crc/machine/client.go
  pkg/crc/machine/console.go
  pkg/crc/machine/fakemachine/client.go
  pkg/crc/machine/start.go
  pkg/crc/machine/state/state.go
  pkg/crc/machine/status.go
  pkg/crc/machine/stop.go
  pkg/crc/machine/sync.go
  pkg/crc/machine/sync_test.go
  pkg/crc/machine/types/types.go
Labels: approved

#2574 api: remove binary protocol server
  cmd/crc/cmd/daemon.go
  pkg/crc/api/api.go
  pkg/crc/api/api_test.go
  pkg/crc/api/types.go
Labels: approved, lgtm

#2583 Handle error from os.UserHomeDir function
  pkg/crc/constants/constants.go
Labels: approved, lgtm

#2585 [e2e] windows cmd with env fix missing semicolon
  test/extended/crc/cmd/cmd.go
Labels: approved, lgtm

#2591 Bump trays to latest versions
  pkg/crc/version/version.go
Labels: approved, lgtm

#2590 Bump hyperkit driver to 0.15.0
  pkg/crc/machine/hyperkit/constants.go
Labels: approved

#2566 Issue #2559 Remove vsock entry from hyperv guest services registry
  pkg/crc/preflight/preflight_windows.go
Labels: approved, lgtm

#2573 api: return state.Stopped when the machine doesnt exist
  pkg/crc/machine/status.go
Labels: approved, has-to-be-in-release, lgtm

#2568 Issue #2565 Create vsock registry entry from msi
  packaging/windows/product.wxs.in
Labels: approved, has-to-be-in-release, lgtm

#2599 Update bundle to 4.8.1 (candidate channel)
  Makefile
  centos_ci.sh
Labels: approved, do-not-merge/hold

#2600 Use ExecuteAsAdmin to remove registry key for vsock
  pkg/crc/preflight/preflight_windows.go
Labels: approved, has-to-be-in-release, lgtm

#2595 Issue #2550 msi: check ram requirement before starting installation
  packaging/windows/product.wxs.in
Labels: approved, lgtm

#2602 Add container images, pull secret size/date and oc get mcp in diag. tarball
  test/extended/util/collect.go
Labels: approved

#2605 Include the new bundle part in msi created due to size increase
  Makefile
  packaging/windows/product.wxs.in
Labels: approved, lgtm

#2603 cut v1.30.0
  Makefile
Labels: approved, do-not-merge/hold, has-to-be-in-release

#2615 docs: Update installation procedure for Windows MSI
  docs/source/topics/proc_installing-codeready-containers.adoc
Labels: approved, lgtm

#2608 mco: delete the leader lease right after start.
  pkg/crc/cluster/cluster.go
  pkg/crc/machine/start.go
Labels: approved, lgtm
