Repository crc-org/crc, pull requests merged in 2021-08, with the labels that each got.

#2619 docs: Clarify `machine-config` Operator support status
  docs/source/topics/con_differences-from-production-openshift-install.adoc
  docs/source/topics/proc_accessing-the-openshift-cluster-with-oc.adoc
Labels: approved, lgtm

#2625 Update bundle to 4.8.3 (candidate channel)
  Makefile
  centos_ci.sh
Labels: approved, lgtm

#2637 Remove step to generate windows flat binary zip
  Makefile
Labels: lgtm, approved

#2638 Update mac (1.0.12) and windows (0.10.0.0) tray versions
  pkg/crc/version/version.go
Labels: approved, has-to-be-in-release

#2633 Update bundle to 4.8.4 (stable channel)
  Makefile
  centos_ci.sh
Labels: approved

#2642 cut 1.31.0
  Makefile
Labels: approved, do-not-merge/hold

#2643 Revert "Include the new bundle part in msi created due to size increase"
  Makefile
  packaging/windows/product.wxs.in
Labels: approved

#2644 cut v1.31.1
  Makefile
Labels: approved

#2647 Fix #2646: return empty responses to prevent JSON deserialization
  pkg/crc/api/api_http.go
Labels: approved

#2650 cut v1.31.2
  Makefile
Labels: lgtm, approved

#2655 crc-embedder: Check number of args passed to 'download'
  cmd/crc-embedder/cmd/download.go
  cmd/crc-embedder/cmd/embed.go
  cmd/crc-embedder/cmd/extract.go
  cmd/crc-embedder/cmd/list.go
  cmd/crc-embedder/cmd/root.go
Labels: lgtm, approved

#2659 api: Split tests in separate functions
  pkg/crc/api/api_http_test.go
Labels: lgtm, approved

#2663 Update bundle version to 4.8.5 (candidate channel)
  Makefile
  centos_ci.sh
Labels: lgtm, approved

#2680 Issue #2666 Fix win edition check in the preflight and msi
  packaging/windows/product.wxs.template
  pkg/crc/preflight/preflight_checks_windows.go
Labels: approved
