Repository crc-org/crc, pull requests merged in 2021-09, with the labels that each got.

#2686 Remove dummy crcbundle (added as part of df77a5392 commit)
  crc_hyperkit_4.8.5.crcbundle
  crc_hyperv_4.8.5.crcbundle
  crc_libvirt_4.8.5.crcbundle
Labels: lgtm, approved

#2668 Don't remove crc-users group and current user from it during upgrade
  packaging/windows/product.wxs.template
Labels: lgtm, approved, has-to-be-in-release

#2694 [e2e] Use executing instead execute for `oc whoami` step
  test/e2e/features/cert_rotation.feature
Labels: lgtm, approved

#2693 Use Select-Object instead of parenthesis to get Hyper-V VM status
  pkg/drivers/hyperv/hyperv_windows.go
Labels: lgtm, approved

#2640 Remove machine config render check for bundle generation
  pkg/crc/cluster/cluster.go
Labels: approved, has-to-be-in-release

#2697 cut v1.32.0
  Makefile
Labels: lgtm, approved

#2616 Hyper-V driver improvements
  pkg/drivers/hyperv/hyperv_windows.go
Labels: lgtm, approved

#2702 Use context to eventually cancel waiting loops
  pkg/crc/cluster/cert_renewal.go
  pkg/crc/cluster/cluster.go
  pkg/crc/cluster/csr.go
  pkg/crc/cluster/kubeadmin_password.go
  pkg/crc/errors/multierror.go
  pkg/crc/errors/multierror_test.go
  pkg/crc/machine/bundle/repository.go
  pkg/crc/machine/generate_bundle.go
  pkg/crc/machine/start.go
  pkg/crc/services/dns/dns.go
  pkg/crc/services/dns/dns_darwin.go
  pkg/crc/ssh/ssh.go
  pkg/libmachine/host/host.go
Labels: lgtm, approved

#2709 bundle: Make sure perms of unpacked bundle are 0755
  pkg/crc/machine/bundle/repository.go
Labels: approved

#2713 preflight: Fix rhel7 detection
  pkg/crc/preflight/preflight_linux.go
Labels: lgtm, approved

#2695 [e2e] Added options to control e2e container execution
  images/build-e2e/README.md
  images/build-e2e/entrypoint.sh
Labels: approved

#2699 [integration] Add container to run integration test within a target host
  Makefile
  images/build-integration/Dockerfile
  images/build-integration/README.md
  images/build-integration/entrypoint.sh
Labels: lgtm, approved

#2721 e2e: Fix 'Clenaup' typo
  images/build-e2e/entrypoint.sh
Labels: lgtm, approved

#2720 cmd:bundle: Use --force-stop rather than --forceStop
  cmd/crc/cmd/bundle/generate.go
Labels: lgtm, approved

#2722 Issue #2687 Modify tray started check to verify if daemon is running
  pkg/crc/preflight/preflight_checks_tray_darwin.go
Labels: approved

#2734 Remove travis CI from repo
  .travis.yml
Labels: lgtm, approved

#2688 ci: Always run 'crc' with '--log-level debug'
  test/e2e/crcsuite/crcsuite.go
  test/e2e/features/basic.feature
  test/e2e/features/cert_rotation.feature
  test/e2e/features/config.feature
  test/e2e/features/proxy.feature
  test/e2e/features/story_marketplace.feature
  test/e2e/features/story_registry.feature
  test/extended/crc/cmd/cmd.go
Labels: lgtm, approved, has-to-be-in-release

#2740 Enable and start vsock and http crc sockets
  pkg/crc/preflight/preflight_checks_linux.go
Labels: lgtm, approved

#2669 Skip setup steps that would trigger a reboot during upgrade
  packaging/windows/WixUI_HK.wxs
  packaging/windows/product.wxs.template
Labels: lgtm, approved

#2754 Update windows tray version to 0.11.0.0
  pkg/crc/version/version.go
Labels: lgtm, approved

#2765 Revert "Use DHCP to configure DNS with user network mode"
  pkg/crc/services/dns/dns.go
  pkg/crc/services/dns/dns_darwin.go
  pkg/crc/services/dns/dns_windows.go
Labels: lgtm, approved

#2766 cut v1.33.1
  Makefile
Labels: lgtm, approved

#2771 proxy: Add fallback to x509.NewCertPool() on Windows
  pkg/crc/network/proxy.go
Labels: lgtm, approved
