Repository crc-org/crc, pull requests merged in 2021-01, with the labels that each got.

#1791 Update http example integration test
  test/integration/features/story_health.feature
Labels: approved, lgtm

#1810 Delete the VM directly without stopping it in most integration tests
  test/integration/features/story_health.feature
  test/integration/features/story_marketplace.feature
  test/integration/features/story_registry.feature
Labels: approved, lgtm

#1809 Update bundle version to 4.6.9
  Makefile
  centos_ci.sh
Labels: approved

#1816 Remove warn flags from the config
  cmd/crc/cmd/config/config.go
  docs/source/topics/con_about-codeready-containers-configuration.adoc
  pkg/crc/preflight/preflight.go
  pkg/crc/preflight/preflight_darwin_test.go
  pkg/crc/preflight/preflight_linux_test.go
  pkg/crc/preflight/preflight_test.go
  pkg/crc/preflight/preflight_windows_test.go
  test/integration/features/config.feature
Labels: approved

#1819 fedora33: Workaround NetworkManager bug with systemd-resolved
  pkg/crc/preflight/preflight_checks_network_linux.go
Labels: approved, lgtm

#1801 Use udev rule to configure the permission and group for /dev/vsock
  pkg/crc/preflight/preflight_linux.go
Labels: approved, lgtm

#1821 Fix destination file for win/mac tray
  pkg/crc/preflight/preflight_checks_tray_darwin.go
  pkg/crc/preflight/preflight_checks_tray_windows.go
Labels: approved, lgtm

#1815 Remove kubelet status check from start
  pkg/crc/machine/start.go
Labels: approved

#1783 Integration: Add check for enabled monitoring stack
  test/integration/features/basic.feature
Labels: approved, lgtm

#1772 doc: Add systemd-resolved description to our DNS reference
  docs/source/topics/ref_dns-configuration.adoc
Labels: approved, lgtm

#1831 Use test write key for non-release builds
  Makefile
  pkg/crc/segment/segment.go
Labels: approved

#1834 simplest macOS package
  .circleci/config.yml
  Makefile
  cmd/crc-embedder/cmd/download.go
  packaging/.gitignore
  packaging/darwin/Distribution
  packaging/darwin/Resources/banner.png
  packaging/darwin/Resources/conclusion.html
  packaging/darwin/Resources/welcome.html
  packaging/darwin/scripts/postinstall
  pkg/crc/constants/constants.go
  pkg/embed/embed.go
Labels: approved

#1797 Upping client,server timeouts to prevent EOFs
  docs/source/topics/proc_setting-up-remote-server.adoc
Labels: ok-to-test

#1839 Add a missing newline to console command
  cmd/crc/cmd/console.go
Labels: lgtm, ok-to-test

#1843 Add segment production key for package target
  Makefile
Labels: approved, lgtm

#1845 doc: Add notice and procedures for usage data collection
  docs/source/topics/proc_setting-up-codeready-containers.adoc
Labels: approved, lgtm

#1844 doc: Update "Starting monitoring" documentation
  docs/source/topics/proc_starting-monitoring-alerting-telemetry.adoc
Labels: approved, lgtm

#1846 cut 1.21.0
  Makefile
Labels: approved

#1841 Check for race conditions when running go test
  Makefile
  appveyor.yml
Labels: approved, lgtm

#1849 Align license title and remove appendix like openshift/origin
  LICENSE
Labels: approved, lgtm

#1857 Use public registry for ubi
  images/dnsmasq/Dockerfile
  images/docs-builder/Dockerfile
Labels: approved, lgtm

#1866 Update bundle from 4.6.9 to 4.6.12
  Makefile
  centos_ci.sh
Labels: approved

#1870 Remove OcBinDir if it's a file
  pkg/crc/machine/bundle/repository.go
  pkg/crc/machine/bundle/repository_test.go
Labels: approved

#1884 ssh: log private keys used for the connection
  pkg/crc/ssh/client.go
Labels: approved, lgtm

#1891 FileExists is true on Windows even with chmod 000
  pkg/os/util_test.go
Labels: approved, lgtm

#1894 diagnose: collect stderr output of container logs
  test/integration/crcsuite/collect.go
Labels: approved, lgtm

#1895 Update the cluster cidr and service network in case of proxy
  pkg/crc/cluster/cluster.go
Labels: approved, lgtm
