Repository crc-org/crc, pull requests merged in 2021-12, with the labels that each got.

#2858 RFC: Hide libMachineAPIClient/CrcBundleMetadata/libmachine.Host from `pkg/crc/machine`
  pkg/crc/machine/console.go
  pkg/crc/machine/delete.go
  pkg/crc/machine/generate_bundle.go
  pkg/crc/machine/ip.go
  pkg/crc/machine/machine.go
  pkg/crc/machine/poweroff.go
  pkg/crc/machine/start.go
  pkg/crc/machine/status.go
  pkg/crc/machine/stop.go
  pkg/crc/machine/virtualmachine.go
Labels: approved

#2873 Docs: update firewalld instructions
  docs/source/topics/proc_setting-up-remote-server.adoc
Labels: lgtm, approved, ok-to-test

#2878 Daemon changes to make podman cni plugin to work with crc
  cmd/crc/cmd/daemon.go
Labels: lgtm, approved

#2884 ci: Try again to use latest google-cloud-sdk rpm
  images/openshift-ci/Dockerfile
Labels: lgtm, approved

#2888 Daemon API: Reregister the settings as part of start/get api call
  pkg/crc/api/api_http.go
  pkg/crc/api/handlers.go
  pkg/crc/api/helpers_test.go
Labels: lgtm, approved

#2893 Status: Add preset info to status cli/api
  cmd/crc/cmd/status.go
  cmd/crc/cmd/status_test.go
  pkg/crc/api/api_client_test.go
  pkg/crc/api/api_http_test.go
  pkg/crc/api/client/types.go
  pkg/crc/api/handlers.go
  pkg/crc/machine/fakemachine/client.go
  pkg/crc/machine/status.go
  pkg/crc/machine/types/types.go
Labels: lgtm, approved

#2900 Update podman to 3.4.2
  Makefile
  pkg/crc/machine/bundle/constants.go
Labels: lgtm, approved

#2902 Update bundle to 4.9.11 (candidate channel)
  Makefile
  centos_ci.sh
Labels: lgtm, approved
