Repository crc-org/crc, pull requests merged in 2021-05, with the labels that each got.

#2298 macOS pkg: check for memory installed
  packaging/darwin/Distribution.in
Labels: approved, lgtm

#2299 cut v1.26.0
  Makefile
Labels: approved

#2306 Remove space before ellipsis (...)
  pkg/crc/cluster/cluster.go
  pkg/crc/cluster/status.go
  pkg/crc/machine/start.go
  pkg/crc/preflight/preflight.go
  test/e2e/features/config.feature
Labels: approved, lgtm

#2302 Add an enum for OpenShift status. Ensure it doesn't change.
  cmd/crc/cmd/status.go
  pkg/crc/api/adapter.go
  pkg/crc/machine/fakemachine/client.go
  pkg/crc/machine/status.go
  pkg/crc/machine/types/types.go
Labels: approved

#2309 Add missing states for Hyper-V, remove state.None usage
  pkg/crc/machine/stop.go
  pkg/drivers/hyperv/hyperv.go
Labels: approved, lgtm

#2308 Remove default operator ignore list for status
  pkg/crc/cluster/clusteroperator.go
  pkg/crc/cluster/clusteroperator_test.go
  pkg/crc/cluster/status.go
  pkg/crc/machine/status.go
Labels: approved, lgtm

#2318 Fix logging.Memory thread-safety
  pkg/crc/logging/inmemory.go
  pkg/crc/logging/inmemory_test.go
Labels: approved, lgtm

#2322 telemetry: send the status of the cluster with action
  pkg/crc/api/client/types.go
  pkg/crc/api/handlers.go
  pkg/crc/api/helpers_test.go
  pkg/crc/segment/segment.go
Labels: approved, lgtm

#2335 Check if running in WSL2 right after checking root
  pkg/crc/preflight/preflight_linux.go
  pkg/crc/preflight/preflight_linux_test.go
Labels: approved

#2341 Update settings help message for network-mode
  pkg/crc/config/settings.go
Labels: approved, lgtm

#2333 Update the cluster name as per oc norms
  pkg/crc/machine/kubeconfig.go
Labels: approved, lgtm

#2345 Update bundle version to 4.7.11
  Makefile
  centos_ci.sh
Labels: approved, do-not-merge/hold

#2348 Report errors when Close() is called on a writable file
  packaging/windows/split.go
  pkg/drivers/hyperv/copy.go
  pkg/embed/embed.go
  pkg/extract/extract.go
  pkg/os/util.go
  test/extended/util/util.go
Labels: approved, lgtm

#2347 Error in Stop() doesn't necessarily mean the VM needs PowerOff()
  pkg/crc/api/adapter.go
  pkg/crc/api/api.go
  pkg/crc/api/api_http.go
  pkg/crc/api/handlers.go
Labels: approved, lgtm

#2349 api: if an action is in progress, use this info. in the status
  pkg/crc/machine/sync.go
  pkg/crc/machine/types/types.go
Labels: approved, lgtm

#2350 Always validate pull secret before storing it in keyring
  pkg/crc/api/api_http.go
  pkg/crc/cluster/pullsecret.go
  pkg/crc/cluster/pullsecret_test.go
Labels: approved, lgtm

#2327 Don't use kubeadmin-passwd file from the bundle
  pkg/crc/cluster/kubeadmin_password.go
  pkg/crc/machine/bundle/copier.go
  pkg/crc/machine/bundle/copier_test.go
  pkg/crc/machine/bundle/metadata.go
  pkg/crc/machine/bundle/metadata_test.go
  pkg/crc/machine/generate_bundle.go
  pkg/crc/machine/machine.go
  pkg/crc/machine/start.go
Labels: approved, has-to-be-in-release

#2361 Bump machine-driver-libvirt to 0.13.1
  pkg/crc/machine/libvirt/constants.go
Labels: approved, has-to-be-in-release, lgtm

#2360 bump windows tray to v0.6.0.0 and macOS tray to v1.0.9
  pkg/crc/version/version.go
Labels: approved, has-to-be-in-release, lgtm

#2363 Update issue template to include triage label
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: approved, priority/trivial, size/S

#2359 Remove windows tray from experimental and enable it by default when using the msi to install
  pkg/crc/config/settings.go
  pkg/crc/preflight/preflight_windows.go
  pkg/crc/preflight/preflight_windows_test.go
Labels: approved, has-to-be-in-release

#2364 cut v1.27.0
  Makefile
Labels: approved, do-not-merge/hold

#2369 Fixes #2368 Change background color of MSI installer images
  packaging/windows/Resources/background.png
  packaging/windows/Resources/background.xcf
  packaging/windows/Resources/banner.png
  packaging/windows/Resources/banner.xcf
Labels: approved, has-to-be-in-release, lgtm, os/windows, priority/trivial, size/S

#2367 Issue #2366 Don't try to download the tray during setup
  pkg/crc/constants/constants_windows.go
  pkg/crc/preflight/preflight_checks_nonlinux.go
  pkg/crc/preflight/preflight_checks_tray_windows.go
Labels: approved, lgtm

#2371 Issue #2370 Don't use custom action to delete install folder during uninstall
  packaging/windows/product.wxs.in
Labels: approved, lgtm
