Repository crc-org/crc, pull requests merged in 2021-06, with the labels that each got.

#2358 Replace mirror link to developer.redhat.com
  pkg/crc/version/version.go
Labels: approved, lgtm

#2390 start: Display help message when preflights fail
  cmd/crc/cmd/start.go
  pkg/os/execerror.go
  test/e2e/features/basic.feature
Labels: approved, lgtm

#2383 Add method to list all bundles available
  pkg/crc/machine/bundle/copier_test.go
  pkg/crc/machine/bundle/metadata.go
  pkg/crc/machine/bundle/metadata_test.go
  pkg/crc/machine/bundle/repository.go
  pkg/crc/machine/bundle/repository_test.go
Labels: approved, lgtm

#2395 Fix release info URI to use `rest/mirror` instead `file`
  pkg/crc/version/version.go
Labels: approved, lgtm

#2355 Add config option to set kubeadmin password for cluster
  cmd/crc/cmd/start.go
  pkg/crc/api/handlers.go
  pkg/crc/cluster/kubeadmin_password.go
  pkg/crc/config/settings.go
  pkg/crc/config/validations.go
  pkg/crc/machine/start.go
  pkg/crc/machine/types/types.go
Labels: approved

#2403 telemetry: report if crc was installed using the installers
  pkg/crc/segment/traits_darwin.go
  pkg/crc/segment/traits_windows.go
  usage-data.adoc
Labels: approved, lgtm

#2362 Change `crc podman-env` to use the root Podman socket
  cmd/crc/cmd/podman_env.go
  pkg/crc/machine/start.go
Labels: approved, lgtm

#2416 Remove fat macOS binary, keep only for the .pkg for release
  Makefile
Labels: approved, lgtm

#2407 Clean kubeconfig file after crc delete
  pkg/crc/machine/delete.go
  pkg/crc/machine/kubeconfig.go
  pkg/crc/machine/kubeconfig_test.go
  pkg/crc/machine/testdata/kubeconfig.in
  pkg/crc/machine/testdata/kubeconfig.out
Labels: approved, has-to-be-in-release, lgtm

#2422 bump windows tray to v0.7.0.0
  pkg/crc/version/version.go
Labels: approved

#2418 Make rootless as default socket for podman-env command
  cmd/crc/cmd/podman_env.go
Labels: approved, lgtm

#2423 cut v1.28.0
  Makefile
Labels: approved, do-not-merge/hold, lgtm

#2415 docs: Expand installation procedure, cover binary and installer
  docs/source/topics/proc_installing-codeready-containers.adoc
Labels: approved, lgtm, status/peer review required

#2440 Check exists bool and not only the error
  pkg/crc/machine/status.go
Labels: approved, lgtm

#2448 Add version check for golangci lint
  Makefile
Labels: approved

#2456 Add missing disk size when starting the VM from the API
  pkg/crc/api/handlers.go
Labels: approved, lgtm

#2467 Update machine-driver-hyperkit to 0.14.0
  pkg/crc/machine/hyperkit/constants.go
Labels: approved, lgtm

#2472 Bump golangci-lint to v1.41.1
  .golangci.yml
  Makefile
  cmd/crc/cmd/start.go
  pkg/crc/adminhelper/hosts.go
  pkg/crc/ssh/keys_windows.go
  pkg/drivers/hyperv/hyperv_windows.go
  pkg/os/launchd/launchd_darwin.go
  test/extended/util/util.go
Labels: approved, lgtm

#2471 Use regex instead string match for stop command
  test/integration/resize_test.go
Labels: approved, lgtm

#2399 Remove system networking mode on macOS
  pkg/crc/config/settings.go
Labels: approved, lgtm

#2476 Add proxy-ca-file to http transport
  cmd/crc/cmd/root.go
  cmd/crc/cmd/start.go
  pkg/crc/segment/segment.go
  pkg/crc/segment/segment_test.go
  pkg/crc/version/version.go
Labels: approved

#2493 Bump windows tray to v0.8.0.0 and macOS tray to v1.0.10
  pkg/crc/version/version.go
Labels: approved, lgtm

#2495 Enclose path with quotes in powershell command for fetching tray version
  pkg/crc/preflight/preflight_checks_tray_windows.go
Labels: approved, lgtm

#2406 Add section on compiling CRC locally to developing.adoc
  developing.adoc
Labels: needs-ok-to-test

#2497 Update bundle to 4.7.16
  Makefile
  centos_ci.sh
Labels: approved, lgtm
