Repository crc-org/crc, pull requests merged in 2021-03, with the labels that each got.

#2033 oc login needs to take username parameter to force basic auth
  cmd/crc/cmd/start.go
  cmd/crc/cmd/start_test.go
Labels: approved, has-to-be-in-release, lgtm

#2035 docs: Fix odo link
  docs/source/meta/product-attributes.adoc
Labels: approved

#2036 oc login needs to take username parameter to force basic auth
  test/e2e/features/basic.feature
Labels: approved, lgtm, ok-to-test

#2040 Bump CRC_VERSION to 1.23.0
  Makefile
Labels: approved

#2034 Bump system trays
  pkg/crc/version/version.go
Labels: approved

#2041 circleci: Update ubuntu image and podman package
  .circleci/config.yml
Labels: approved

#2042 images:docs_builder: Use 'ignorelist' rather than 'whitelist'
  images/docs-builder/Dockerfile
  images/docs-builder/entrypoint.sh
  images/docs-builder/links_ignorelist.json
Labels: approved, lgtm

#2044 [images/docs-builder] Bump nodejs module to 14
  images/docs-builder/Dockerfile
Labels: approved, lgtm

#2046 Load the kubeadmin password in a more robust way: remove extra spaces
  pkg/crc/machine/bundle/metadata.go
Labels: approved, lgtm

#2052 Convert Debug to Info for wait for apiserver availablility
  pkg/crc/cluster/cluster.go
Labels: approved, lgtm

#2055 bump macOS tray version to 1.0.2
  pkg/crc/version/version.go
Labels: approved, lgtm

#1924 Add check if crc daemon is running and bind to default endpoints
  pkg/crc/preflight/preflight_checks_nondarwin.go
  pkg/crc/preflight/preflight_linux.go
  pkg/crc/preflight/preflight_linux_test.go
  pkg/crc/preflight/preflight_windows.go
  pkg/crc/preflight/preflight_windows_test.go
Labels: approved

#2069 Bump macos tray to 1.0.3
  pkg/crc/version/version.go
Labels: approved

#2029 Remove ClusterOperator kind from CVO overrides
  pkg/crc/cluster/monitoring.go
Labels: approved, lgtm

#2061 Improve status reporting
  pkg/crc/machine/status.go
Labels: approved

#2074 Bump the minimal supported macOS version
  docs/source/topics/ref_minimum-system-requirements.adoc
Labels: approved, lgtm

#2076 machine: Fix error handling in Stop()
  pkg/crc/machine/stop.go
Labels: approved

#2083 Use the same error field for json errors and backend errors
  pkg/crc/api/handlers.go
  pkg/crc/api/types.go
Labels: approved, lgtm

#2060 Improve logging of daemon protocol
  pkg/crc/api/api.go
Labels: approved, lgtm

#2106 When stop returns an error try to use poweroff to shutdown vm
  pkg/crc/api/adapter.go
Labels: approved, lgtm

#2100 Retain 100 log messages in the memory and serve them through the API
  cmd/crc/cmd/daemon.go
  pkg/crc/api/api.go
  pkg/crc/api/api_test.go
  pkg/crc/api/handlers.go
  pkg/crc/api/types.go
  pkg/crc/logging/inmemory.go
  pkg/crc/logging/inmemory_test.go
  pkg/crc/logging/logging.go
Labels: approved, lgtm

#2107 Update bundle from 4.7.1 to 4.7.2
  Makefile
  centos_ci.sh
Labels: approved, lgtm

#2072 Update kubeadmin password for each fresh start
  go.mod
  go.sum
  pkg/crc/cluster/kubeadminPassword.go
  pkg/crc/machine/bundle/metadata.go
  pkg/crc/machine/console.go
  pkg/crc/machine/machine.go
  pkg/crc/machine/start.go
  vendor/golang.org/x/crypto/bcrypt/base64.go
  vendor/golang.org/x/crypto/bcrypt/bcrypt.go
  vendor/golang.org/x/crypto/chacha20/chacha_arm64.go
  vendor/golang.org/x/crypto/chacha20/chacha_noasm.go
  vendor/golang.org/x/crypto/chacha20/chacha_ppc64le.go
  vendor/golang.org/x/crypto/chacha20/chacha_s390x.go
  vendor/golang.org/x/crypto/curve25519/curve25519_amd64.go
  vendor/golang.org/x/crypto/curve25519/curve25519_noasm.go
  vendor/golang.org/x/crypto/ed25519/ed25519.go
  vendor/golang.org/x/crypto/ed25519/ed25519_go113.go
  vendor/golang.org/x/crypto/internal/subtle/aliasing.go
  vendor/golang.org/x/crypto/internal/subtle/aliasing_purego.go
  vendor/golang.org/x/crypto/poly1305/bits_compat.go
  vendor/golang.org/x/crypto/poly1305/bits_go1.13.go
  vendor/golang.org/x/crypto/poly1305/mac_noasm.go
  vendor/golang.org/x/crypto/poly1305/sum_amd64.go
  vendor/golang.org/x/crypto/poly1305/sum_ppc64le.go
  vendor/golang.org/x/crypto/poly1305/sum_s390x.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/modules.txt
Labels: approved, lgtm

#2110 Bump minimum macOS version in the installer
  packaging/darwin/Distribution.in
Labels: approved, lgtm

#2098 [Doc] Remove `as=system:admin` for developer user
  docs/source/topics/proc_accessing-the-openshift-cluster-with-oc.adoc
Labels: approved, lgtm

#2103 Bump gvisor-tap-vsock vendoring: remove debug log
  go.mod
  go.sum
  vendor/github.com/code-ready/gvisor-tap-vsock/pkg/services/dns/dns.go
  vendor/github.com/code-ready/gvisor-tap-vsock/pkg/tap/ip_pool.go
  vendor/modules.txt
Labels: approved

#2056 Note systemd-resolved usage for RHEL 8
  docs/source/meta/product-attributes.adoc
  docs/source/topics/ref_dns-configuration.adoc
Labels: approved, lgtm, ok-to-test

#2102 #2004 Extract then rename can be too fast for Windows antivirus
  pkg/crc/machine/bundle/repository.go
Labels: approved, has-to-be-in-release, lgtm

#2114 Update internal registry access doc
  docs/source/topics/proc_accessing-the-internal-openshift-registry.adoc
Labels: approved, has-to-be-in-release, lgtm

#2121 Do not timestamp integration output files
  test/integration/testsuite_test.go
Labels: approved, lgtm

#2115 Issue #2112: Check VM disk size from inside the VM
  test/integration/resize_test.go
  test/integration/utilities_test.go
Labels: approved, has-to-be-in-release

#2064 Issue #2054 Ask user to run setup when 'autostart-tray' set to true
  cmd/crc/cmd/config/config.go
  pkg/crc/tray/util_darwin.go
  pkg/crc/tray/util_linux.go
  pkg/crc/tray/util_windows.go
Labels: approved, lgtm

#2122 Remove unused import
  cmd/crc/cmd/config/config.go
Labels: approved, lgtm

#2124 Revert "Validate sudo access before using it with a real command"
  pkg/os/exec.go
Labels: approved, lgtm

#2096 Change the root check error message
  pkg/crc/preflight/preflight_checks_nonwin.go
Labels: approved, lgtm

#2134 hyperkit: Revert back to 0.12.11 machine driver
  pkg/crc/machine/hyperkit/constants.go
Labels: approved, lgtm

#2132 cut v1.24.0
  Makefile
Labels: approved, do-not-merge/hold, lgtm

#2135 Revert "Rotate logs only if deletion was successful"
  cmd/crc/cmd/delete.go
  pkg/crc/logging/logging.go
Labels: approved

#2142 test: give more time to kubelet to restart user pods
  test/e2e/features/story_health.feature
Labels: approved

#2141 machine: Fix growRootFileSystem() on Windows
  pkg/crc/machine/start.go
Labels: approved, lgtm

#2140 telemetry: enable tracking between Red Hat products
  pkg/crc/segment/segment.go
  pkg/crc/segment/segment_test.go
Labels: approved, lgtm

#2136 Issue #1698 docs: Add reserved IP subnets
  docs/source/topics/assembly_networking.adoc
  docs/source/topics/ref_reserved-ip-subnets.adoc
Labels: approved, lgtm

#2146 drivers: don't start the VM when creating it
  pkg/crc/machine/hyperkit/constants.go
  pkg/crc/machine/libvirt/constants.go
  pkg/drivers/hyperv/hyperv.go
  pkg/libmachine/libmachine.go
Labels: approved, lgtm

#2159 [E2E] Fix expected output on e2e setup scenario for windows
  test/e2e/features/basic.feature
Labels: approved, lgtm

#2155 Update bundle from 4.7.2 to 4.7.4
  Makefile
  centos_ci.sh
Labels: approved

#2165 Remove unnecessary second issue template
  .github/ISSUE_TEMPLATE/custom.md
Labels: approved

#2150 docs: Simplify haproxy configuration
  docs/source/topics/proc_setting-up-remote-server.adoc
Labels: approved

#2173 Fix compilation errors after 2 merges
  pkg/crc/machine/sync.go
  pkg/crc/machine/sync_test.go
Labels: approved, lgtm
