Repository crc-org/crc, pull requests merged in 2022-11, with the labels that each got.

#3404 Remove use of io/ioutil
  cmd/crc-embedder/cmd/embed.go
  cmd/crc/cmd/daemon.go
  cmd/crc/cmd/status_test.go
  pkg/compress/compress_test.go
  pkg/crc/api/api_client_test.go
  pkg/crc/api/api_http_test.go
  pkg/crc/api/client/client.go
  pkg/crc/api/helpers.go
  pkg/crc/cache/cache.go
  pkg/crc/cluster/cluster.go
  pkg/crc/cluster/clusteroperator_test.go
  pkg/crc/cluster/kubeadmin_password.go
  pkg/crc/cluster/pullsecret.go
  pkg/crc/cluster/pullsecret_test.go
  pkg/crc/config/viper_config.go
  pkg/crc/config/viper_config_test.go
  pkg/crc/machine/bundle/copier.go
  pkg/crc/machine/bundle/repository.go
  pkg/crc/machine/bundle/repository_test.go
  pkg/crc/machine/generate_bundle.go
  pkg/crc/machine/kubeconfig_test.go
  pkg/crc/machine/start.go
  pkg/crc/network/nameservers.go
  pkg/crc/network/proxy.go
  pkg/crc/preflight/preflight_checks_linux.go
  pkg/crc/preflight/preflight_ubuntu_linux.go
  pkg/crc/segment/segment.go
  pkg/crc/segment/segment_test.go
  pkg/crc/ssh/client.go
  pkg/crc/ssh/ssh.go
  pkg/crc/version/version.go
  pkg/drivers/vfkit/driver_darwin.go
  pkg/extract/extract_test.go
  pkg/libmachine/persist/filestore.go
  pkg/libmachine/persist/filestore_test.go
  pkg/os/copy_test.go
  pkg/os/launchd/launchd_darwin.go
  pkg/os/linux/release_info.go
  pkg/os/util.go
  pkg/os/util_windows.go
  pkg/os/windows/powershell/powershell_windows.go
  test/extended/util/collect.go
  test/extended/util/e2e_logger.go
  test/extended/util/fileops.go
  test/extended/util/prepare.go
  test/extended/util/util.go
Labels: approved

#3412 cmd/version: OpenShift version should not be preset dependent
  cmd/crc/cmd/root.go
  cmd/crc/cmd/version.go
  pkg/crc/api/handlers.go
Labels: approved

#3420 Update openshift bundle to 4.11.13 (fast channel)
  Makefile
  pkg/crc/machine/bundle/constants.go
Labels: lgtm, approved

#3422 Update okd bundle to 4.11.0-0.okd-2022-11-05-030711
  Makefile
Labels: lgtm, approved

#3392 Fetch console URL form daemon for 'console' cmd
  cmd/crc/cmd/console.go
  cmd/crc/cmd/console_test.go
  pkg/crc/api/api_http_test.go
  pkg/crc/api/client/client.go
  pkg/crc/api/client/types.go
  pkg/crc/api/handlers.go
  pkg/crc/machine/exists.go
  test/mocks/api/client.go
Labels: lgtm, approved, ok-to-test

#3409 Allow to use file sharing for mac 13.x
  pkg/drivers/vfkit/driver_darwin.go
Labels: lgtm, approved

#3424 [e2e] fix SCC constraints on deployments
  test/e2e/features/story_openshift.feature
  test/testdata/hello.yaml
  test/testdata/httpd-example.yaml
Labels: lgtm, approved

#3426 update 4.11.13 bundle hash
  pkg/crc/machine/bundle/constants.go
Labels: approved, do-not-merge/hold

#3427 cut v2.11.0
  Makefile
Labels: lgtm, approved
