Repository crc-org/crc, pull requests merged in 2022-05, with the labels that each got.

#3150 Mac/Windows: Check if daemon able to serve after it starts
  pkg/crc/preflight/preflight_checks_darwin.go
  pkg/crc/preflight/preflight_checks_nonlinux.go
  pkg/crc/preflight/preflight_daemon_task_check_windows.go
Labels: lgtm, approved

#3164 bump tray version to 1.2.3
  pkg/crc/version/version.go
Labels: lgtm, approved

#3169 Update the openshift bundle to 4.10.12 (stable channel)
  Makefile
Labels: lgtm, approved

#3168 bump tray version to 1.2.4
  pkg/crc/version/version.go
Labels: lgtm, approved

#3170 [e2e] fix output check for cleanup command on windows
  test/e2e/features/basic.feature
Labels: lgtm, approved, QE

#3171 update download url and hash for 4.10.12 bundles
  pkg/crc/machine/bundle/constants.go
Labels: lgtm, approved

#3173 cut 2.3.0
  Makefile
Labels: lgtm, approved

#3176 Improve a few user-visible messages
  pkg/crc/machine/start.go
  pkg/crc/preflight/preflight_windows.go
Labels: approved

#3185 Update URLs from cloud to console.redhat.com
  README.adoc
  pkg/crc/constants/constants.go
Labels: lgtm, needs-ok-to-test

#3184 add github actions workflow status badges to README
  README.adoc
Labels: lgtm, approved

#3188 docs: Update `odo` usage information
  docs/source/topics/proc_deploying-sample-application-with-odo.adoc
Labels: lgtm, approved

#3177 Daemon: Add containers.internal DNS record for podman-4.x to work
  cmd/crc/cmd/daemon.go
Labels: approved, do-not-merge/hold

#3193 bump tray version to 1.2.5
  pkg/crc/version/version.go
Labels: lgtm, approved
