Repository crc-org/crc, pull requests merged in 2022-09, with the labels that each got.

#3081 [Integration] Podman preset tests
  Makefile
  test/integration/podman_test.go
  test/integration/resize_test.go
  test/integration/testsuite_test.go
  test/integration/utilities_test.go
Labels: lgtm, approved

#3338 Fixes #3281 remove alpha from preset config option help
  pkg/crc/config/settings.go
Labels: lgtm, approved

#3340 update OWNERS_ALIASES info
  OWNERS_ALIASES
Labels: lgtm, approved

#3339 e2e: execute crc setup as an isolated command
  test/e2e/crcsuite/crcsuite.go
  test/e2e/features/basic.feature
  test/extended/crc/cmd/cmd.go
Labels: lgtm, approved, has-to-be-in-release, QE

#3332 Vsock: Add alternate http/https port in case 80/443 in use
  cmd/crc/cmd/start.go
  pkg/crc/api/handlers.go
  pkg/crc/config/callbacks.go
  pkg/crc/config/settings.go
  pkg/crc/config/types.go
  pkg/crc/config/validations.go
  pkg/crc/constants/constants.go
  pkg/crc/machine/start.go
  pkg/crc/machine/types/types.go
  pkg/crc/machine/vsock.go
Labels: lgtm, approved, has-to-be-in-release

#3351 Update podman version to 4.2.0
  Makefile
Labels: lgtm, approved, has-to-be-in-release

#3353 Validation: Use validation path in case windows path in used
  pkg/crc/validation/validation.go
Labels: lgtm, approved

#3355 Makefile: Add build tags for build integration target
  Makefile
Labels: lgtm, approved
