Repository crc-org/crc, pull requests merged in 2022-08, with the labels that each got.

#3275 update Podman bundle to 4.1.1
  Makefile
Labels: lgtm, approved

#3290 bump tray to 1.2.8
  pkg/crc/version/version.go
Labels: lgtm

#3297 Update openshift bundle to 4.11.0
  Makefile
  pkg/crc/machine/bundle/constants.go
Labels: lgtm, approved

#3300 Fixes #3298 Changes Windows release preflight message
  pkg/crc/preflight/preflight_windows.go
  test/e2e/features/basic.feature
Labels: lgtm, approved

#3299 cut v2.7.0
  Makefile
Labels: lgtm, approved, do-not-merge/hold

#3302 Update the kernel args to instance config during stop
  pkg/crc/machine/driver_darwin.go
  pkg/crc/machine/driver_linux.go
  pkg/crc/machine/driver_windows.go
  pkg/crc/machine/stop.go
Labels: lgtm, approved

#3303 cut v2.7.1
  Makefile
Labels: lgtm, approved

#3325 doc: Clarify when no_proxy=.testing needs to be set
  docs/source/topics/proc_starting-behind-proxy.adoc
Labels: lgtm, approved

#3324 Update okd version to 4.11.0-0.okd-2022-08-20-022919
  Makefile
Labels: lgtm, approved

#3327 cut 2.8.0
  Makefile
Labels: lgtm, approved
