Repository crc-org/crc, pull requests merged in 2022-03, with the labels that each got.

#3039 go-mod: Update the gvisor-tap
  go.mod
  go.sum
  vendor/github.com/mdlayher/vsock/CHANGELOG.md
  vendor/github.com/mdlayher/vsock/conn_linux.go
  vendor/github.com/mdlayher/vsock/go.mod
  vendor/github.com/mdlayher/vsock/vsock.go
  vendor/github.com/mdlayher/vsock/vsock_others.go
  vendor/modules.txt
Labels: lgtm, approved

#3040 add entitlements for tray-electron
  packaging/CodeReady_Containers.app.entitlements
  packaging/package.sh
Labels: approved

#3042 cut 1.99.3
  Makefile
Labels: lgtm, approved

#3045 Doc Deploy: Use main branch instead master
  .circleci/config.yml
Labels: lgtm, approved

#3050 Fix release json sample file to have correct podman version
  release-info.json.sample
Labels: lgtm, approved

#3056 Update bundle to 4.10.3 (candidate channel)
  Makefile
  centos_ci.sh
Labels: approved

#3061 Update bundle links to 4.10.3 and 3.4.4 podman (mirror.openshift)
  pkg/crc/machine/bundle/constants.go
Labels: lgtm, approved

#3060 Packaging Mac: Use 'Applications' instead 'application'
  packaging/darwin/Resources/conclusion.html
Labels: lgtm, approved

#3057 docs: Update introductory content with preset information
  docs/source/meta/product-attributes.adoc
  docs/source/topics/con_about-codeready-containers.adoc
  docs/source/topics/con_differences-from-production-openshift-install.adoc
Labels: approved, has-to-be-in-release

#3062 bump electron tray to v1.2.0
  pkg/crc/version/version.go
Labels: lgtm, approved

#3063 cut 2.0.0
  Makefile
Labels: lgtm, approved, do-not-merge/hold

#3064 ignore error when removing tray related launchd plist file
  pkg/crc/preflight/preflight_darwin.go
Labels: lgtm, approved

#3066 Mac Preflight: Check if plist file exist before removing it
  pkg/crc/preflight/preflight_darwin.go
Labels: lgtm, approved

#3065 cut 2.0.1
  Makefile
Labels: lgtm, approved

#3069 Improve macos tray removal code
  pkg/crc/preflight/preflight_darwin.go
Labels: lgtm, approved

#3073 Update to Openshift 4.10.4 (candidate channel)
  Makefile
  centos_ci.sh
Labels: lgtm, approved

#3059 Make user mode networking default for dev build
  pkg/crc/config/settings.go
Labels: lgtm, approved

#3094 docs: fix crc preset set command
  docs/source/topics/proc_changing-the-selected-preset.adoc
Labels: lgtm, approved, needs-ok-to-test
