Repository crc-org/crc, pull requests merged in 2022-06, with the labels that each got.

#3199 update electron tray to 1.2.6
  pkg/crc/version/version.go
Labels: lgtm

#3200 cut 2.4.0
  Makefile
Labels: lgtm, approved

#3201 build: fix signing arm64 pkg on an amd64 mac
  Makefile
  packaging/.gitignore
  packaging/package.sh
Labels: approved

#3202 cut 2.4.1
  Makefile
Labels: lgtm, approved

#3203 Cluster Operator: Ignore 'RecentBackup' as operator status
  pkg/crc/cluster/clusteroperator.go
Labels: lgtm, approved

#3189 Detect mismatch of bundle version from Makefile and bundle/constant.go
  pkg/crc/machine/bundle/metadata.go
  pkg/download/download.go
Labels: lgtm, approved

#3225 [Doc] Remove podman/docker dependency to access internal registry
  docs/source/topics/proc_accessing-the-internal-openshift-registry.adoc
Labels: lgtm, approved

#3228 [e2e] Remove podman dependency on story_registry feature
  test/e2e/features/story_registry.feature
Labels: lgtm, approved

#3233 machine: Fix upload of /tmp/routes-controller.json
  pkg/crc/machine/start.go
Labels: lgtm, approved

#3234 cut 2.5.0
  Makefile
Labels: lgtm, approved

#3232 doc: Rework RHEL support statement
  docs/source/topics/ref_minimum-system-requirements.adoc
Labels: lgtm, approved

#3138 Change CodeReady Containers to CRC in extended test folder
  test/extended/crc/ux/installer/applescripts/install.applescript
  test/extended/crc/ux/installer/installer_windows.go
  test/extended/crc/ux/notification/notification_windows.go
  test/extended/crc/ux/tray/tray_windows.go
Labels: lgtm, approved

#3240 ubuntu: Fix apparmor rule for podman preset
  pkg/crc/preflight/preflight_ubuntu_linux.go
  pkg/crc/preflight/preflight_ubuntu_linux_test.go
Labels: lgtm, approved
