Repository crc-org/crc, pull requests merged in 2022-04, with the labels that each got.

#3097 Update openshift bundle to 4.10.6 (stable channel)
  Makefile
  centos_ci.sh
Labels: lgtm, approved

#3095 Mac: Enable daemon service to run as soon as user login
  pkg/os/launchd/launchd_darwin.go
Labels: approved, has-to-be-in-release

#3090 docs: Add OpenShift preset as a prerequisite to applicable procedures
  docs/source/topics/proc_accessing-the-internal-openshift-registry.adoc
  docs/source/topics/proc_accessing-the-openshift-cluster-with-oc.adoc
  docs/source/topics/proc_accessing-the-openshift-web-console.adoc
  docs/source/topics/proc_deploying-sample-application-with-odo.adoc
  docs/source/topics/proc_setting-up-remote-server.adoc
Labels: lgtm, approved

#3108 bump electron-tray to 1.2.1
  pkg/crc/version/version.go
Labels: lgtm, approved

#3110 appveyor fixes
  appveyor.yml
  update-go-version.sh
Labels: lgtm, approved

#3113 Update the bundles checksum and url for 4.10.6
  pkg/crc/machine/bundle/constants.go
Labels: approved

#3107 cut v2.1.0
  Makefile
Labels: approved, do-not-merge/hold

#3118 [integration] fix default bundle location value on integration container
  images/build-integration/entrypoint.sh
Labels: lgtm, approved, has-to-be-in-release, QE

#3120 Replace CodeReady Containers to CRC
  README.adoc
  cmd/crc/cmd/constants.go
  cmd/crc/cmd/daemon_windows.go
  cmd/crc/cmd/setup.go
  cmd/crc/cmd/setup_test.go
  cmd/crc/cmd/version.go
  cmd/crc/cmd/version_test.go
  images/build-e2e/Dockerfile
  images/build-integration/Dockerfile
  images/build/Dockerfile
  images/dnsmasq/Dockerfile
  images/docs-builder/Dockerfile
  images/squid/Dockerfile
  pkg/crc/cluster/pullsecret.go
  pkg/crc/config/settings.go
  pkg/crc/machine/machine.go
  pkg/crc/machine/start.go
  pkg/crc/preflight/preflight_checks_darwin.go
  pkg/crc/preflight/preflight_checks_linux.go
  pkg/crc/preflight/preflight_checks_nonwin.go
  pkg/crc/preflight/preflight_darwin.go
  pkg/crc/preflight/preflight_linux.go
Labels: lgtm, approved

#3128 Tray: bump version renamed to Red Hat OpenShift Local
  pkg/crc/version/version.go
Labels: approved, has-to-be-in-release

#3121 docs: Rename CodeReady Containers to "CRC"
  docs/source/meta/product-attributes.adoc
Labels: lgtm, approved

#3119 Update the openshift bundle to 4.10.9 (stable)
  Makefile
Labels: approved, has-to-be-in-release

#3125 MacOS: rename to Red Hat OpenShift Local
  Makefile
  packaging/OpenShift_Local.app.entitlements
  packaging/darwin/Distribution.in
  packaging/darwin/Resources/banner.png
  packaging/darwin/Resources/conclusion.html
  packaging/darwin/welcome.html.in
  packaging/package.sh
  pkg/crc/constants/constants_darwin.go
  test/extended/crc/ux/tray/tray_unix.go
Labels: lgtm, approved, has-to-be-in-release

#3129 Packaging: [Mac] Remove old CodeReady Containers folder from applications
  packaging/darwin/postinstall.in
Labels: lgtm, approved, has-to-be-in-release

#3130 MacOS: correct entitlements
  packaging/Red_Hat_OpenShift_Local.app.entitlements
Labels: lgtm, approved

#3127 Windows: rename to Red Hat OpenShift Local
  packaging/windows/Resources/background.png
  packaging/windows/Resources/background.xcf
  packaging/windows/Resources/banner.png
  packaging/windows/Resources/banner.xcf
  packaging/windows/Resources/icon.ico
  packaging/windows/WixUI_HK.wxs
  packaging/windows/product.wxs.template
  pkg/crc/constants/constants_windows.go
Labels: approved, do-not-merge/hold, has-to-be-in-release

#3132 Update bundle link and sha256sum for 4.10.9
  pkg/crc/machine/bundle/constants.go
Labels: lgtm, approved

#3133 Windows: Remove an existing task as part of fixDaemonTaskInstalled
  pkg/crc/preflight/preflight_daemon_task_check_windows.go
Labels: lgtm, approved

#3136 Integration: Replace 'CodeReady Containers' to CRC
  test/e2e/features/basic.feature
  test/integration/resize_test.go
Labels: lgtm, approved

#3134 cut v2.2.0
  Makefile
Labels: lgtm, approved

#3141 Check for daemonTaskRunning returns nil if correct version of daemon is already running
  pkg/crc/preflight/preflight_daemon_task_check_windows.go
Labels: lgtm, approved, do-not-merge/hold

#3143 cut 2.2.1
  Makefile
Labels: lgtm, approved

#3151 Issue #3149 check for existence of daemon process in checkIfDaemonPlistFileExists
  pkg/crc/preflight/preflight_checks_darwin.go
Labels: lgtm, approved, release-blocker

#3146 Windows: Make sure task exist before stop and removing it
  pkg/crc/preflight/preflight_daemon_task_check_windows.go
Labels: lgtm, approved, release-blocker

#3152 cut v2.2.2
  Makefile
Labels: lgtm, approved
