Repository crc-org/crc, pull requests merged in 2022-02, with the labels that each got.

#2986 docs: Update terminology, use "instance" and "container runtime"
  docs/source/topics/assembly_accessing-the-openshift-cluster.adoc
  docs/source/topics/assembly_configuring-codeready-containers.adoc
  docs/source/topics/assembly_using-codeready-containers.adoc
  docs/source/topics/con_about-codeready-containers-configuration.adoc
  docs/source/topics/con_about-codeready-containers.adoc
  docs/source/topics/con_differences-from-production-openshift-install.adoc
  docs/source/topics/proc_accessing-the-internal-openshift-registry.adoc
  docs/source/topics/proc_accessing-the-openshift-cluster-with-oc.adoc
  docs/source/topics/proc_accessing-the-openshift-web-console.adoc
  docs/source/topics/proc_configuring-the-instance.adoc
  docs/source/topics/proc_configuring-usage-data-collection.adoc
  docs/source/topics/proc_deleting-the-instance.adoc
  docs/source/topics/proc_deleting-the-virtual-machine.adoc
  docs/source/topics/proc_deploying-sample-application-with-odo.adoc
  docs/source/topics/proc_setting-up-codeready-containers.adoc
  docs/source/topics/proc_starting-monitoring.adoc
  docs/source/topics/proc_starting-the-instance.adoc
  docs/source/topics/proc_stopping-the-instance.adoc
  docs/source/topics/proc_stopping-the-virtual-machine.adoc
  docs/source/topics/proc_troubleshooting-bundle-version-mismatch.adoc
  docs/source/topics/proc_troubleshooting-expired-certificates.adoc
  docs/source/topics/proc_troubleshooting-unknown-issues.adoc
  docs/source/topics/proc_upgrading-codeready-containers.adoc
  docs/source/topics/ref_dns-configuration.adoc
  docs/source/topics/ref_minimum-system-requirements.adoc
  docs/source/topics/snip_crc-delete.adoc
Labels: lgtm, approved

#2601 Improve crc stop message for already stopped cluster
  pkg/crc/machine/stop.go
Labels: lgtm, approved

#3008 Update openshift bundle to 4.9.18 (stable channel)
  Makefile
  centos_ci.sh
Labels: lgtm, approved

#3007 e2e: Fix mismatch around cluster and instance
  test/integration/resize_test.go
Labels: approved

#3011 [cherry-pick] Improve crc stop message for already stopped cluster
  pkg/crc/machine/stop.go
Labels: lgtm, approved

#3015 Update golangci-lint to latest version
  Makefile
  pkg/crc/cache/cache.go
Labels: approved

#3023 cut v1.40.0
  Makefile
Labels: lgtm, approved, do-not-merge/hold

#3032 bump electron-tray to 1.1.0
  pkg/crc/version/version.go
Labels: lgtm, approved

#3029 Used named pipe to expose podman sock on windows
  cmd/crc/cmd/podman_env.go
  go.mod
  go.sum
  pkg/crc/constants/constants.go
  pkg/crc/machine/vsock.go
  vendor/github.com/Microsoft/go-winio/file.go
  vendor/github.com/Microsoft/go-winio/go.mod
  vendor/github.com/Microsoft/go-winio/go.sum
  vendor/github.com/Microsoft/go-winio/hvsock.go
  vendor/github.com/Microsoft/go-winio/pkg/guid/guid.go
  vendor/github.com/Microsoft/go-winio/pkg/guid/guid_nonwindows.go
  vendor/github.com/Microsoft/go-winio/pkg/guid/guid_windows.go
  vendor/github.com/containers/gvisor-tap-vsock/pkg/services/forwarder/ports.go
  vendor/github.com/containers/gvisor-tap-vsock/pkg/sshclient/npipe_unsupported.go
  vendor/github.com/containers/gvisor-tap-vsock/pkg/sshclient/npipe_windows.go
  vendor/github.com/containers/gvisor-tap-vsock/pkg/sshclient/ssh_forwarder.go
  vendor/github.com/containers/gvisor-tap-vsock/pkg/types/handshake.go
  vendor/modules.txt
Labels: lgtm, approved, has-to-be-in-release

#3031 Update Openshift(4.9.18) and podman(3.4.4) bundles
  Makefile
  pkg/crc/machine/bundle/constants.go
Labels: lgtm, approved, has-to-be-in-release

#3033 cut 1.99.2 - beta release
  Makefile
Labels: approved, do-not-merge/hold

#3037 bump electron-tray to 1.1.2
  pkg/crc/version/version.go
Labels: lgtm, approved, has-to-be-in-release
