Repository crc-org/crc, pull requests merged in 2022-01, with the labels that each got.

#2918 API: Add preset info as part of machine client
  pkg/crc/machine/client.go
  pkg/crc/machine/fakemachine/client.go
  pkg/crc/machine/sync.go
  pkg/crc/machine/sync_test.go
Labels: lgtm, approved

#2921 delete: Ignore errors loading bundle metadata
  pkg/crc/machine/delete.go
  pkg/crc/machine/virtualmachine.go
Labels: lgtm, approved

#2904 e2e fix bundle default path with blank spaces
  test/e2e/crcsuite/crcsuite.go
Labels: lgtm, has-to-be-in-release

#2919 Update openshift bundle to 4.9.12 (candidate channel)
  Makefile
  centos_ci.sh
Labels: lgtm, approved

#2929 Update hyperkit and crc-hyperkit driver binary version
  pkg/crc/machine/hyperkit/constants.go
Labels: lgtm, approved

#2928 cut v1.38.0
  Makefile
Labels: lgtm, approved

#2932 docs: Use "control plane" instead of "master node"
  docs/source/topics/con_differences-from-production-openshift-install.adoc
Labels: lgtm, approved

#2931 docs: Create sections for usage data collection
  docs/source/meta/product-attributes.adoc
  docs/source/topics/assembly_administrative-tasks.adoc
  docs/source/topics/assembly_installation.adoc
  docs/source/topics/con_about-usage-data-collection.adoc
  docs/source/topics/proc_configuring-usage-data-collection.adoc
  docs/source/topics/proc_setting-up-codeready-containers.adoc
  docs/source/topics/proc_starting-monitoring.adoc
Labels: approved

#2903 Vsock: Add ip to local port mapping
  pkg/crc/machine/vsock.go
Labels: lgtm, approved

#2941 podman:generate new random bearer token for cockpit
  pkg/crc/cluster/podman.go
  pkg/crc/machine/start.go
Labels: approved, has-to-be-in-release

#2943 Release ports during delete operation
  pkg/crc/machine/delete.go
  pkg/crc/machine/vsock.go
Labels: approved

#2955 Preflight: Improve bundle download to recover from ctrl+c and resume
  pkg/crc/preflight/preflight_checks_common.go
Labels: lgtm, approved

#2953 Vsock: Don't bind port < 1024 with localhost
  pkg/crc/machine/vsock.go
Labels: approved

#2954 Segment: Send error to debug log instead stderr
  pkg/crc/segment/segment.go
Labels: lgtm, approved

#2964 Cut dev 1.99.1
  Makefile
Labels: approved

#2974 cut v1.39.0
  Makefile
Labels: lgtm, approved, do-not-merge/hold
