Repository crc-org/crc, pull requests merged in 2022-07, with the labels that each got.

#3242 docs: Update M1 support statement: only the Podman preset is supported
  docs/source/topics/ref_minimum-system-requirements.adoc
Labels: lgtm, approved

#3243 docs: Document enabling override Operators
  docs/source/topics/assembly_administrative-tasks.adoc
  docs/source/topics/proc_enabling-override-operators.adoc
Labels: lgtm

#3260 Fix AddUserToHypervAdminGroup custom action
  packaging/windows/product.wxs.template
Labels: ok-to-test

#3261 cut v2.6.0
  Makefile
Labels: lgtm, approved

#3262 fix gomod2rpmdeps installation
  Makefile
  tools/bin/.gitignore
Labels: lgtm, approved

#3268 bundle: Don't extract container image layer twice
  pkg/crc/image/image.go
Labels: lgtm
