Repository crc-org/crc, pull requests merged in 2023-09, with the labels that each got.

#3814 start daemon posh script with RemoteSigned execution policy
  pkg/crc/preflight/preflight_daemon_task_check_windows.go
Labels: lgtm, approved

#3806 Add app routes for microshift preset
  pkg/crc/constants/constants.go
  pkg/crc/machine/bundle/repository.go
Labels: lgtm, approved

#3815 preflight: add cleanup check to kill daemon process
  pkg/crc/preflight/preflight_daemon_task_check_windows.go
  pkg/crc/preflight/preflight_windows.go
  pkg/crc/preflight/preflight_windows_test.go
Labels: lgtm, approved, has-to-be-in-release

#3818 update openshift and microshift bundles to 4.13.9
  Makefile
Labels: lgtm, approved

#3819 Revert "proxy: Add fallback to x509.NewCertPool() on Windows"
  pkg/crc/network/httpproxy/proxy.go
Labels: lgtm, approved

#3817 Refactor: Move logic to get default image uri to constants
  pkg/crc/constants/constants.go
  pkg/crc/image/image.go
  pkg/crc/machine/bundle/metadata.go
Labels: approved

#3836 docs: Antora extension setting some AsciiDoc attributes
  antora-playbook.yml
  docs/extensions/get-versions.js
Labels: approved

#3847 docs: added goatcounter
  docs/supplemental-ui/partials/header-content.hbs
Labels: kind/documentation

#3848 Updated OKD version to 4.13.0-0.okd-2023-09-03-082426
  Makefile
Labels: lgtm, approved

#3841 e2e: Fix syntax for commands to check cluster certs
  test/e2e/features/story_openshift.feature
  test/e2e/testsuite/testsuite.go
Labels: priority/minor, lgtm, approved, QE

#3820 Add persistent volume size option to config
  cmd/crc/cmd/start.go
  pkg/crc/config/settings.go
  pkg/crc/config/validations.go
  pkg/crc/constants/constants.go
  pkg/crc/machine/start.go
  pkg/crc/machine/types/types.go
  pkg/crc/validation/validation.go
Labels: lgtm, approved

#3808 Issue #3742 Improve preset config change message
  pkg/crc/config/callbacks.go
  test/integration/podman_test.go
Labels: lgtm, approved
