Repository crc-org/crc, pull requests merged in 2023-06, with the labels that each got.

#3694 config: Return exit code 0 when getting default value
  cmd/crc/cmd/config/get.go
Labels: lgtm, approved

#3691 segment: return error if cached idenitfier is not 8 bytes long
  pkg/crc/segment/segment.go
Labels: lgtm, approved

#3666 Microshift: add disk resize functionality
  pkg/crc/machine/start.go
Labels: lgtm, approved

#3696 config: Improve default value message
  cmd/crc/cmd/config/get.go
Labels: approved, has-to-be-in-release

#3706 Fix LVM resize error due to fs utilities do not support renamed devices
  pkg/crc/machine/start.go
Labels: approved, has-to-be-in-release

#3708 Update OKD bundle to 4.13.0-0.okd-2023-06-04-080300
  Makefile
Labels: lgtm, approved, has-to-be-in-release

#3721 daemon: set execution time limit of daemon task to indefinite
  pkg/crc/preflight/preflight_daemon_task_check_windows.go
Labels: lgtm, approved

#3712 Deploy router controller resource from bundle
  pkg/crc/machine/start.go
Labels: lgtm, approved

#3729 bump openshift and microshift bundle version to 4.13.3
  Makefile
Labels: lgtm, approved

#3727 microshift: Use api.crc.testing kubeconfig to connect to cluster
  pkg/crc/machine/kubeconfig.go
  pkg/crc/machine/start.go
Labels: lgtm, approved, has-to-be-in-release

#3722 GrowLVForMicroshift: Change disk '/dev/vda' to '/dev/sda' for windows
  pkg/crc/machine/start.go
Labels: lgtm, approved, has-to-be-in-release

#3732 Update gvisor-tap-vsock dependency to 0.6.2
  go.mod
  go.sum
  vendor/github.com/containers/gvisor-tap-vsock/pkg/services/dns/dns.go
  vendor/github.com/containers/gvisor-tap-vsock/pkg/tap/protocols.go
  vendor/github.com/containers/gvisor-tap-vsock/pkg/tap/switch.go
  vendor/github.com/containers/gvisor-tap-vsock/pkg/transport/listen_darwin.go
  vendor/github.com/containers/gvisor-tap-vsock/pkg/transport/listen_linux.go
  vendor/github.com/containers/gvisor-tap-vsock/pkg/transport/listen_windows.go
  vendor/github.com/containers/gvisor-tap-vsock/pkg/transport/unixgram_unix.go
  vendor/github.com/containers/gvisor-tap-vsock/pkg/types/configuration.go
  vendor/github.com/containers/gvisor-tap-vsock/pkg/virtualnetwork/vfkit.go
  vendor/github.com/miekg/dns/client.go
  vendor/github.com/miekg/dns/version.go
  vendor/golang.org/x/crypto/ssh/common.go
  vendor/golang.org/x/crypto/ssh/mac.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sync/errgroup/go120.go
  vendor/golang.org/x/sync/errgroup/pre_go120.go
  vendor/golang.org/x/sys/cpu/endian_little.go
  vendor/golang.org/x/sys/unix/mkall.sh
  vendor/golang.org/x/sys/unix/mkerrors.sh
  vendor/golang.org/x/sys/unix/syscall_linux.go
  vendor/golang.org/x/sys/unix/syscall_openbsd.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_linux.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_mips64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_ppc64.s
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_riscv64.s
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/syscall_windows.go
  vendor/golang.org/x/sys/windows/zsyscall_windows.go
  vendor/modules.txt
Labels: lgtm, approved, has-to-be-in-release

#3738 Revert "Deploy router controller resource from bundle"
  pkg/crc/machine/start.go
Labels: lgtm, approved

#3739 cut v2.22.1
  Makefile
Labels: lgtm, approved
