Repository crc-org/crc, pull requests merged in 2023-12, with the labels that each got.

#3934 update openshift and microshift bundle to 4.14.3
  Makefile
Labels: approved

#3937 cut v2.30.0
  Makefile
Labels: lgtm, approved

#3939 [QE] fix #3938 bash wrong syntax on integration oci entrypoint script
  images/build-integration/entrypoint.sh
Labels: lgtm, approved

#3943 Update admin-helper to latest release
  pkg/crc/version/version.go
Labels: lgtm, approved

#3933 Build e2e and integration test images as part of PR checks
  .github/workflows/build-tests.yml
Labels: priority/major, lgtm, approved, QE

#3948 update admin-helper to 0.5.1
  pkg/crc/version/version.go
Labels: lgtm, approved
