Repository crc-org/crc, pull requests merged in 2023-03, with the labels that each got.

#3512 split installation of tray into separate selectable feature
  packaging/windows/WixUI_HK.wxs
  packaging/windows/product.wxs.template
Labels: lgtm, approved

#3523 Update preflight_windows.go
  pkg/crc/preflight/preflight_windows.go
  pkg/os/windows/win32/domains_windows.go
Labels: lgtm, ok-to-test

#3531 Use correct tag for route controller image as per openshift release
  pkg/crc/machine/start.go
Labels: lgtm, has-to-be-in-release

#3536 Integration: Add checks for the initial start of the VM with custom values (memory, cpus, disk)
  test/integration/resize_test.go
Labels: lgtm, approved

#3547 Fixes #3546 #3550 Add option to allow progressbars to be forced during download and uncompression of the bundle (setup phase)
  cmd/crc/cmd/setup.go
  pkg/crc/cache/cache.go
  pkg/crc/cluster/pullsecret.go
  pkg/crc/input/input.go
  pkg/crc/segment/segment.go
  pkg/download/download.go
  pkg/extract/extract.go
  pkg/extract/extract_test.go
  pkg/os/terminal/terminal.go
  pkg/os/util.go
Labels: kind/bug, size/S, priority/critical, lgtm, approved

#3564 Issue #3514 Remove crc instance entries from known_hosts file
  pkg/crc/machine/delete.go
Labels: lgtm, approved
