Repository crc-org/crc, pull requests merged in 2023-08, with the labels that each got.

#3778 update openshift and microshift bundles to 4.13.6
  Makefile
Labels: lgtm

#3780 cut v2.24.1
  Makefile
Labels: lgtm, approved

#3782 e2e: Add debug steps to verify the cert with CA
  test/e2e/features/story_openshift.feature
Labels: lgtm, approved

#3781 Fix error when num of CPU not match progress bars
  cmd/crc/cmd/status.go
Labels: priority/minor, lgtm, approved

#3788 bump libvirt driver to 0.13.6
  pkg/crc/machine/libvirt/constants.go
Labels: lgtm, approved

#3775 daemon: start daemon from a powershell script that hides window
  pkg/crc/preflight/preflight_daemon_task_check_windows.go
  pkg/crc/preflight/preflight_windows.go
  pkg/crc/preflight/preflight_windows_test.go
Labels: lgtm, approved

#3789 cut v2.25.0
  Makefile
Labels: lgtm, approved, do-not-merge/hold

#3798 e2e test: Ignore network-mode config property for non linux platform
  test/e2e/testsuite/testsuite.go
Labels: lgtm, approved
