Repository crc-org/crc, pull requests merged in 2023-05, with the labels that each got.

#3590 CI: Make sure oc/podman env command works
  .github/workflows/macos-microshift.yml
Labels: lgtm, approved

#3642 preflight: add check to see if admin-helper namedpipe is accessible
  pkg/crc/preflight/preflight_checks_windows.go
  pkg/crc/preflight/preflight_windows.go
Labels: lgtm, approved

#3646 Update microshift bundle to 4.12.15
  Makefile
Labels: lgtm, approved

#3651 download: Fix p/s progress bar suffix
  pkg/download/download.go
Labels: lgtm, approved

#3648 cut v2.19.0
  Makefile
Labels: approved

#3675 Update OKD bundle to 4.12.0-0.okd-2023-02-18-033438
  Makefile
Labels: lgtm, approved

#3679 bug-3635 fix generating kubeadmin-password for OKD preset
  pkg/crc/machine/start.go
Labels: lgtm, approved, ok-to-test

#3680 Update microshift, openshift and OKD bundles
  Makefile
Labels: lgtm, approved
