Repository crc-org/crc, pull requests merged in 2023-01, with the labels that each got.

#3470 Adding OKD to the presets-related documentation
  docs/source/meta/product-attributes.adoc
  docs/source/topics/con_about-presets.adoc
  docs/source/topics/proc_changing-the-selected-preset.adoc
Labels: lgtm, approved, needs-ok-to-test

#3475 Add flag `--components` to `crc-embedder` tool
  cmd/crc-embedder/cmd/download.go
  cmd/crc-embedder/cmd/embed.go
Labels: approved

#3462 [e2e] added repetitions to ensure the state of the cluster
  test/extended/crc/cmd/cmd.go
  test/extended/util/util.go
Labels: lgtm, approved, has-to-be-in-release, QE

#3478 Update introduction section and title of README
  README.adoc
Labels: lgtm, approved

#3481 update openshift bundle to 4.12.0
  pkg/crc/machine/bundle/constants.go
Labels: lgtm, approved

#3482 Update podman bundle version to 4.3.1
  Makefile
Labels: lgtm, approved

#3486 bump openshift version to 4.12.0 in Makefile
  Makefile
Labels: lgtm, approved

#3487 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: lgtm, approved

#3488 Fix telemetry on linux
  Makefile
Labels: lgtm, approved

#3495 podman-env: Add missing '--root'
  cmd/crc/cmd/podman_env.go
Labels: lgtm, approved
