Repository crc-org/crc, pull requests merged in 2023-04, with the labels that each got.

#3574 CI: add microshift preset for workflow
  .github/workflows/macos-microshift.yml
Labels: lgtm, approved

#3578 Update microshift flow with pull secret
  .github/workflows/macos-microshift.yml
Labels: lgtm, approved

#3583 CI: use dummy pull secret for microshift workflow
  .github/workflows/macos-microshift.yml
Labels: lgtm, approved

#3580 config/settings: Add microshift preset to helper
  pkg/crc/config/settings.go
  pkg/crc/config/validations.go
  pkg/crc/preset/preset.go
Labels: lgtm, approved, has-to-be-in-release

#3596 Start: use the router image as per openshift version for microshift preset
  pkg/crc/machine/start.go
Labels: lgtm, approved

#3601 Remove Read and Write timeout from the daemon API server
  cmd/crc/cmd/daemon.go
Labels: lgtm, approved

#3603 cut v2.17.0
  Makefile
Labels: lgtm, approved

#3609 build: Use release binary for 'packagedir' target
  Makefile
Labels: lgtm, approved

#3610 OKD preset added to GetBundleType
  pkg/crc/machine/bundle/metadata.go
  pkg/crc/machine/bundle/metadata_test.go
Labels: needs-ok-to-test

#3616 bump microshift openshift to 4.12.13 and update bundle hashes
  Makefile
  pkg/crc/machine/bundle/constants.go
Labels: lgtm, approved

#3620 Start: Remove the podman-machine marker file
  pkg/crc/machine/start.go
Labels: lgtm, approved

#3614 vsock: expose remote podman ssh-tunnel connection to local unix socket
  pkg/crc/machine/vsock.go
Labels: lgtm, approved
