Repository crc-org/crc, pull requests merged in 2024-10, with the labels that each got.

#4383 mark some tests only for releases
  test/e2e/features/basic.feature
Labels: lgtm, approved

#4387 Update openshift to 4.17.0 and microshift to 4.16.14
  Makefile
Labels: lgtm, approved

#4386 fix junit format for reports
  images/build-e2e/Containerfile
  images/build-e2e/common/filter.xsl
  images/build-e2e/lib/darwin/run.sh
  images/build-e2e/lib/linux/run.sh
  images/build-e2e/lib/windows/run.ps1
  images/build-integration/Containerfile
  images/build-integration/common/filter.xsl
  images/build-integration/lib/darwin/run.sh
  images/build-integration/lib/linux/run.sh
  images/build-integration/lib/windows/run.ps1
Labels: lgtm, approved

#4404 Doc: Add instruction to access service from host to crc instance
  docs/modules/getting_started/pages/networking.adoc
  docs/modules/getting_started/partials/proc_connecting-to-host.adoc
Labels: lgtm

#4403 [QE] limit log size for test reports
  images/build-e2e/common/filter.xsl
  images/build-integration/common/filter.xsl
Labels: lgtm, approved

#4421 cut v2.43.0
  Makefile
Labels: lgtm, approved

#4400 fix (crc/machine) : KubeContext left in invalid state after crc stop (#1569)
  pkg/crc/machine/kubeconfig.go
  pkg/crc/machine/kubeconfig_test.go
  pkg/crc/machine/stop.go
  pkg/crc/machine/stop_test.go
  pkg/crc/machine/testdata/kubeconfig-without-api-crc-testing-cluster-domain
  test/e2e/features/basic.feature
  test/e2e/testsuite/testsuite.go
Labels: ok-to-test
