Repository crc-org/crc, pull requests merged in 2024-09, with the labels that each got.

#4357 Remove manual creation of routes-controller manifest
  pkg/crc/machine/start.go
Labels: lgtm

#4362 fix: Propagation for labelFiler param
  images/build-integration/lib/darwin/run.sh
  images/build-integration/lib/linux/run.sh
  images/build-integration/lib/windows/run.ps1
Labels: lgtm, approved

#4375 [QE] fix typo on windows-e2e gh action flow.
  .github/workflows/windows-e2e.yml
Labels: lgtm

#4369 Upload qe images when code merged to main
  .github/workflows/windows-artifacts.yml
Labels: approved

#4379 [QE]fix short of registry name in windows-artifact action
  .github/workflows/windows-artifacts.yml
Labels: approved
