Repository crc-org/crc, pull requests merged in 2024-07, with the labels that each got.

#4254 Spec: Append arch info for admin-helper and libvirt driver
  packaging/rpm/crc.spec.in
Labels: lgtm, approved

#4248 [QE] fix can't catch error for "oc login"
  test/extended/util/util.go
Labels: lgtm, approved

#4252 [qe]e2e: wait longer for monitoring operator
  test/e2e/features/basic.feature
Labels: lgtm, approved

#4256 set output encodig for powershell to utf-8
  pkg/os/windows/powershell/powershell_windows.go
Labels: lgtm, approved

#4268 libvirt: Fix machine driver command name
  go.mod
  go.sum
  pkg/crc/machine/libvirt/constants.go
  vendor/github.com/crc-org/machine/libmachine/drivers/plugin/localbinary/plugin.go
  vendor/modules.txt
Labels: lgtm, approved

#4273 build: replace amd64 with GOARCH in make target 'release'
  Makefile
Labels: lgtm, approved

#4269 Show MicroShift version as part of 'version' command
  cmd/crc/cmd/version.go
  cmd/crc/cmd/version_test.go
  pkg/crc/api/api_client_test.go
  pkg/crc/api/api_http_test.go
  pkg/crc/api/client/types.go
  pkg/crc/api/handlers.go
  test/integration/testsuite_test.go
Labels: approved, ok-to-test

#4272 clusteroperator: Ignore EvaluationConditionsDetected condition
  pkg/crc/cluster/clusteroperator.go
Labels: lgtm, approved

#4257 new action that push qe images for new tag
  .github/workflows/qe-image.yml
Labels: lgtm, approved

#4280 Issue #4279 Fix case sensitive WSL2 validation check
  pkg/crc/preflight/preflight_checks_linux.go
Labels: lgtm, approved, ok-to-test

#4288 Update libvirt driver to 0.13.9
  images/rpmbuild/Containerfile.in
  pkg/crc/machine/libvirt/constants.go
Labels: lgtm, approved

#4290 build: Fix binaries not being rebuilt even when there are source changes
  Makefile
Labels: lgtm, approved
