Repository crc-org/crc, pull requests merged in 2024-12, with the labels that each got.

#4493 CI: update macOS-12 to macOS-14
  .github/workflows/macos-installer.yml
  .github/workflows/make-check.yml
Labels: lgtm, approved

#4496 Use all configured ipv4 dns services
  go.mod
  go.sum
  vendor/github.com/containers/gvisor-tap-vsock/pkg/services/dns/dns.go
  vendor/github.com/containers/gvisor-tap-vsock/pkg/services/dns/dns_config_unix.go
  vendor/github.com/containers/gvisor-tap-vsock/pkg/services/dns/dns_config_windows.go
  vendor/github.com/containers/gvisor-tap-vsock/pkg/sshclient/ssh_forwarder.go
  vendor/github.com/containers/gvisor-tap-vsock/pkg/utils/retry.go
  vendor/github.com/fsnotify/fsnotify/.cirrus.yml
  vendor/github.com/fsnotify/fsnotify/.editorconfig
  vendor/github.com/fsnotify/fsnotify/.gitattributes
  vendor/github.com/fsnotify/fsnotify/.gitignore
  vendor/github.com/fsnotify/fsnotify/CHANGELOG.md
  vendor/github.com/fsnotify/fsnotify/CONTRIBUTING.md
  vendor/github.com/fsnotify/fsnotify/backend_fen.go
  vendor/github.com/fsnotify/fsnotify/backend_inotify.go
  vendor/github.com/fsnotify/fsnotify/backend_kqueue.go
  vendor/github.com/fsnotify/fsnotify/backend_other.go
  vendor/github.com/fsnotify/fsnotify/backend_windows.go
  vendor/github.com/fsnotify/fsnotify/fsnotify.go
  vendor/github.com/fsnotify/fsnotify/internal/darwin.go
  vendor/github.com/fsnotify/fsnotify/internal/debug_darwin.go
  vendor/github.com/fsnotify/fsnotify/internal/debug_dragonfly.go
  vendor/github.com/fsnotify/fsnotify/internal/debug_freebsd.go
  vendor/github.com/fsnotify/fsnotify/internal/debug_kqueue.go
  vendor/github.com/fsnotify/fsnotify/internal/debug_linux.go
  vendor/github.com/fsnotify/fsnotify/internal/debug_netbsd.go
  vendor/github.com/fsnotify/fsnotify/internal/debug_openbsd.go
  vendor/github.com/fsnotify/fsnotify/internal/debug_solaris.go
  vendor/github.com/fsnotify/fsnotify/internal/debug_windows.go
  vendor/github.com/fsnotify/fsnotify/internal/freebsd.go
  vendor/github.com/fsnotify/fsnotify/internal/internal.go
  vendor/github.com/fsnotify/fsnotify/internal/unix.go
  vendor/github.com/fsnotify/fsnotify/internal/unix2.go
  vendor/github.com/fsnotify/fsnotify/internal/windows.go
  vendor/github.com/fsnotify/fsnotify/mkdoc.zsh
  vendor/github.com/fsnotify/fsnotify/system_bsd.go
  vendor/github.com/fsnotify/fsnotify/system_darwin.go
  vendor/modules.txt
Labels: ok-to-test

#4495 chore : Update CRC GitHub issue template to be more interactive (#4494)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/enhancement.yml
  .github/ISSUE_TEMPLATE/task.yml
Labels: lgtm, approved

#4477 Update the publicDNSQueryURI in DNS Check to https://quay.io
  pkg/crc/services/dns/dns.go
Labels: lgtm, approved

#4468 [QE] update github action for linux arm64 tests
  .github/workflows/linux-qe-template.yml
  .github/workflows/linux-qe-test.yml
Labels: lgtm, approved

#4515 [QE] fix PR check status for linux-arm64 not shows all
  .github/workflows/linux-qe-template.yml
Labels: lgtm, approved

#4511 virtualmachine: Add logging message in case getBundleMetadataFromDriver fails
  pkg/crc/machine/virtualmachine.go
Labels: lgtm, approved

#4516 chore : Update pull request template to remove link giving 404
  .github/pull_request_template.md
Labels: lgtm

#4479 fix (status) : Log info in CRC status for OKD preset (#3626)
  cmd/crc/cmd/status.go
  cmd/crc/cmd/status_test.go
Labels: needs-ok-to-test
