Repository crc-org/crc, pull requests merged in 2024-11, with the labels that each got.

#4417 fix (test/extended/util) : shell doesn't parse command output ending without newline (#4416)
  test/extended/util/shell.go
  test/extended/util/shell_test.go
Labels: ok-to-test

#4432 [QE] check postprocess program availability
  images/build-e2e/lib/darwin/run.sh
  images/build-e2e/lib/linux/run.sh
  images/build-integration/lib/darwin/run.sh
  images/build-integration/lib/linux/run.sh
Labels: lgtm, approved

#4456 images/squid: Use centos-stream9 instead 8 (EOL)
  images/squid/Dockerfile
Labels: lgtm, approved

#4414 test (e2e) : Add E2E test for java app deploy workflow using Eclipse JKube (#4397)
  test/e2e/features/application_deployment.feature
  test/testdata/jkube-kubernetes-build-resources.yaml
Labels: ok-to-test

#4320 add GitHub action that use Testing Farm
  .github/workflows/linux-qe-template.yml
  .github/workflows/linux-qe-test.yml
  .github/workflows/windows-artifacts.yml
Labels: approved

#4463 [QE] fix github action of linux arm64 tests
  .github/workflows/linux-qe-template.yml
Labels: lgtm, approved

#4437 Ignore virtualization check for arm64 for Linux platform
  pkg/crc/preflight/preflight_checks_linux.go
Labels: lgtm, approved

#4467 fix (daemon) : Add logging to provide additional information for non-200 status codes (#3766)
  cmd/crc/cmd/custom_response_writer.go
  cmd/crc/cmd/custom_response_writer_test.go
  cmd/crc/cmd/daemon.go
  cmd/crc/cmd/daemon_test.go
Labels: lgtm, approved, needs-ok-to-test

#4405 bundle download & decompression: added Context argument
  cmd/crc-embedder/cmd/embed.go
  pkg/compress/compress_test.go
  pkg/crc/cache/cache.go
  pkg/crc/image/image.go
  pkg/crc/machine/bundle/metadata.go
  pkg/crc/machine/bundle/repository.go
  pkg/crc/machine/bundle/repository_test.go
  pkg/crc/machine/start.go
  pkg/crc/preflight/preflight_checks_common.go
  pkg/download/download.go
  pkg/extract/extract.go
  pkg/extract/extract_test.go
  pkg/os/copy.go
  test/extended/util/util.go
Labels: lgtm, approved

#4471 feat (dns) : Add `host.crc.testing` to `/etc/hosts` (#4410)
  pkg/crc/machine/bundle/metadata.go
  pkg/crc/machine/bundle/metadata_test.go
  pkg/crc/services/dns/dns.go
  pkg/crc/services/dns/dns_test.go
Labels: lgtm, approved, needs-ok-to-test

#4474 fix: Download bundle without specifying tag
  pkg/crc/machine/bundle/metadata.go
  pkg/crc/machine/bundle/metadata_test.go
  pkg/crc/machine/start.go
  pkg/crc/preflight/preflight_checks_common.go
  pkg/crc/validation/validation.go
Labels: approved, needs-ok-to-test

#4489 doc : Use GitHub recommended keywords in pull request template to automatically link related issues (#4488)
  .github/pull_request_template.md
Labels: lgtm, approved
