Repository crc-org/crc, pull requests merged in 2024-01, with the labels that each got.

#3953 network_darwin: Remove dead code
  pkg/drivers/vfkit/network_darwin.go
Labels: lgtm, approved

#3952 update admin-helper to 0.5.2
  pkg/crc/version/version.go
Labels: approved

#3910 Merge kubeconfigs using clientcmd.ModifyConfig
  pkg/crc/machine/kubeconfig.go
  pkg/crc/machine/kubeconfig_test.go
Labels: lgtm, approved, ok-to-test

#3958 Update openshift/microshift bundle to 4.14.7 (stable channel)
  Makefile
Labels: lgtm, approved

#3959 cut v2.31.0
  Makefile
Labels: lgtm, approved

#3968 Fix docs-related make targets so they run on MacOS
  Makefile
Labels: lgtm, needs-ok-to-test

#3955 Turn off terminal raw mode on Windows after started progressbar pool
  cmd/crc/cmd/status.go
Labels: approved

#3963 update crc-driver-libvirt to 0.13.7
  pkg/crc/machine/libvirt/constants.go
Labels: lgtm, approved

#3967 📖 Enhance docs
  README.adoc
  docs/README.adoc
  docs/modules/getting_started/pages/introducing.adoc
  docs/modules/getting_started/partials/con_differences-from-production-openshift-install.adoc
Labels: lgtm, needs-ok-to-test
