Repository crc-org/crc, pull requests merged in 2024-04, with the labels that each got.

#4059 Update OKD version to 4.15.0-0.okd-2024-02-23-163410
  Makefile
Labels: approved

#4090 [e2e] Change tag for httpd image on openshift story
  test/e2e/features/story_openshift.feature
  test/e2e/testsuite/testsuite.go
Labels: lgtm, approved

#4091 Avoid using syscall.Sysctl to get macOS version
  pkg/os/darwin/release_info.go
Labels: lgtm, approved

#4102 CI: Add .snyk file to consumed by openshift ci's security scanning
  .snyk
Labels: lgtm, approved

#4125 Chocolatey: Update project url for crc spec
  packaging/chocolatey/crc/crc.nuspec.in
Labels: has-to-be-in-release
