Repository crc-org/crc, pull requests merged in 2025-07, with the labels that each got.

#4827 systemd: Add state for activating service
  pkg/crc/systemd/states/state.go
  pkg/crc/systemd/systemd_linux_test.go
Labels: lgtm

#4801 context: use background() consistently
  cmd/crc-embedder/cmd/embed.go
  pkg/compress/compress_test.go
  pkg/crc/cache/cache.go
  pkg/crc/machine/bundle/repository_test.go
  pkg/crc/preflight/preflight_checks_common.go
  pkg/extract/extract_test.go
  pkg/os/copy.go
  test/extended/util/util.go
Labels: ok-to-test

#4859 cut v2.53.0
  Makefile
Labels: lgtm, approved
