Repository crc-org/crc, pull requests merged in 2025-04, with the labels that each got.

#4715 Fix duplicate imports
  pkg/crc/machine/types/types.go
  pkg/crc/preflight/preflight_darwin.go
Labels: lgtm, approved, needs-ok-to-test

#4722 Fix another duplicate import
  test/e2e/testsuite/testsuite.go
Labels: lgtm, needs-ok-to-test

#4714 Remove extraneous .ObjectMeta references
  pkg/crc/cluster/cert_renewal.go
  pkg/crc/cluster/clusteroperator.go
Labels: needs-ok-to-test

#4721 [QE] install xsltprox for e2e xml result format
  images/build-e2e/lib/linux/run.sh
Labels: lgtm, approved

#4604 test (e2e) : add more assertions to verify crc status output
  test/e2e/features/basic.feature
  test/e2e/testsuite/testsuite.go
Labels: lgtm, approved
