Repository crc-org/crc, pull requests merged in 2025-03, with the labels that each got.

#4653 test (e2e) : add missing comma in `run.ps1` PowerShell param block
  images/build-e2e/lib/windows/run.ps1
Labels: lgtm

#4655 Update openshift/microshift bundle version to 4.18.1
  Makefile
Labels: lgtm

#4635 Verify if binary exists before executing
  pkg/os/exec.go
  pkg/os/exec_test.go
Labels: approved, ok-to-test

#4641 ci : remove step for uploading gh context artifact (#4615)
  .github/workflows/linux-qe-template.yml
  .github/workflows/windows-artifacts.yml
  .github/workflows/windows-qe-tpl.yml
Labels: lgtm, approved

#4601 fix (daemon) : Add `docker.internal` entry to virtual network DNS config (#3784)
  cmd/crc/cmd/daemon.go
  cmd/crc/cmd/daemon_test.go
Labels: approved

#4628 test (machine) : add some unit tests for growing lvm size based on `persistent-volume-size` config option in microshift preset
  pkg/crc/config/validations_test.go
  pkg/crc/machine/start.go
  pkg/crc/machine/start_test.go
Labels: approved

#4678 [QE]remove okd preset test on arm64
  images/build-e2e/lib/darwin/run.sh
  images/build-e2e/lib/linux/run.sh
  images/build-e2e/lib/windows/run.ps1
  test/e2e/features/config.feature
Labels: lgtm, approved
