Repository crc-org/crc, pull requests merged in 2025-02, with the labels that each got.

#4595 Spec: use inbuild gobuildid to generate build id with -B option
  packaging/rpm/crc.spec.in
Labels: approved

#4596 refactor: replace custom slice Contains method with `slices.Contains`
  pkg/crc/cluster/clusteroperator.go
  pkg/crc/machine/bundle/repository.go
  pkg/crc/machine/kubeconfig.go
  pkg/crc/manpages/manpages_unix.go
  pkg/crc/preflight/preflight_checks_network_linux.go
  pkg/strings/strings.go
  pkg/strings/strings_test.go
Labels: lgtm, approved

#4603 fix (status) : Fix incorrect data shown on running `crc status` command
  pkg/crc/machine/status.go
Labels: lgtm, needs-ok-to-test

#4607 Clean filepath before reading the content
  pkg/crc/machine/bundle/repository.go
Labels: lgtm

#4614 cut v2.47.0
  Makefile
Labels: lgtm

#4570 [QE] update pr check on linux-arm64
  .github/workflows/linux-qe-template.yml
  .github/workflows/windows-artifacts.yml
Labels: approved

#4631 start.go: Set chronyd in manual mode
  pkg/crc/machine/start.go
Labels: lgtm

#4633 test (e2e) : Use pinned version of crc while executing e2e tests (#4629)
  images/build-e2e/lib/darwin/run.sh
  images/build-e2e/lib/linux/run.sh
  images/build-e2e/lib/windows/run.ps1
Labels: lgtm

#4611 test (e2e) : move manpage checks to a separate scenario (#4608)
  test/e2e/features/basic.feature
  test/e2e/features/manpages.feature
Labels: lgtm

#4636 test (e2e) : Add steps in Application Deployment Scenario to verify NodePort
  test/e2e/features/application_deployment.feature
Labels: lgtm, approved
